### ISSUE TITLE
Failed to start distributed training job 

### ISSUE THREAD

**Issue by eric-haibin-lin** [bytedance/byteps#138]
**Describe the bug**
I got the following error when launching a distributed training job. 
```
[2019-10-29 01:02:51.983028: F byteps/common/nccl_manager.cc:120] Check failed: r == ncclSuccess NCCL error: unhandled system error
Aborted
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/byteps/launcher/launch.py", line 35, in worker
    subprocess.check_call(command, env=my_env, stdout=sys.stdout, stderr=sys.stderr, shell=True)
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'python3 -u run_pretraining.py --data=/fsx/datasets/part-000.npz --data_eval=/fsx/datasets/book-wiki-split-2k-v3/*.dev, --optimizer bertadam --warmup_ratio 0.2843 --num_steps 7032 --ckpt_interval 300000000 --dtype float16 --ckpt_dir /fsx/bert/haibinlin/worker_mxnet:bps-dba1787-mx-1.5-v1.1-cu90-81a7b1c/59344c4/perf --lr 0.000007 --total_batch_size 8192 --total_batch_size_eval 8192 --accumulate 1 --model bert_24_1024_16 --max_seq_length 128 --max_predictions_per_seq 20 --num_data_workers 4 --no_compute_acc --comm_backend byteps --log_interval 1 --eval_use_npz --verbose' returned non-zero exit status 134

[2019-10-29 01:02:52.100588: F byteps/common/nccl_manager.cc:120] Check failed: r == ncclSuccess NCCL error: unhandled system error
Aborted
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/byteps/launcher/launch.py", line 35, in worker
    subprocess.check_call(command, env=my_env, stdout=sys.stdout, stderr=sys.stderr, shell=True)
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'python3 -u run_pretraining.py --data=/fsx/datasets/part-000.npz --data_eval=/fsx/datasets/book-wiki-split-2k-v3/*.dev, --optimizer bertadam --warmup_ratio 0.2843 --num_steps 7032 --ckpt_interval 300000000 --dtype float16 --ckpt_dir /fsx/bert/haibinlin/worker_mxnet:bps-dba1787-mx-1.5-v1.1-cu90-81a7b1c/59344c4/perf --lr 0.000007 --total_batch_size 8192 --total_batch_size_eval 8192 --accumulate 1 --model bert_24_1024_16 --max_seq_length 128 --max_predictions_per_seq 20 --num_data_workers 4 --no_compute_acc --comm_backend byteps --log_interval 1 --eval_use_npz --verbose' returned non-zero exit status 134

[2019-10-29 01:02:52.242300: F byteps/common/nccl_manager.cc:120] Check failed: r == ncclSuccess NCCL error: unhandled system error
Aborted
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/byteps/launcher/launch.py", line 35, in worker
    subprocess.check_call(command, env=my_env, stdout=sys.stdout, stderr=sys.stderr, shell=True)
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'python3 -u run_pretraining.py --data=/fsx/datasets/part-000.npz --data_eval=/fsx/datasets/book-wiki-split-2k-v3/*.dev, --optimizer bertadam --warmup_ratio 0.2843 --num_steps 7032 --ckpt_interval 300000000 --dtype float16 --ckpt_dir /fsx/bert/haibinlin/worker_mxnet:bps-dba1787-mx-1.5-v1.1-cu90-81a7b1c/59344c4/perf --lr 0.000007 --total_batch_size 8192 --total_batch_size_eval 8192 --accumulate 1 --model bert_24_1024_16 --max_seq_length 128 --max_predictions_per_seq 20 --num_data_workers 4 --no_compute_acc --comm_backend byteps --log_interval 1 --eval_use_npz --verbose' returned non-zero exit status 134


```

**To Reproduce**
1. 
2. 
3. 

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS:
 - GCC version:
 - CUDA and NCCL version:
 - Framework (TF, PyTorch, MXNet):

**Additional context**

**Comment by eric-haibin-lin** [comment]
I cannot reproduce the issue now. Closing it for now.
