### ISSUE TITLE
Missing id() op in bytescheduler.torch.optimizer.py

### ISSUE THREAD

**Issue by un-knight** [bytedance/byteps#143]
**Describe the bug**
In the `bypteps.bytescheduler.torch.optimizer` modular, there are missing `id()` ops for parameter to get parameter memory address before accessing to `self._parameter_names`, which will cause runtime error:

```
Traceback (most recent call last):
  File "/usr/local/byteps/example/pytorch/benchmark_bytescheduler.py", line 134, in <module>
    timeit.timeit(benchmark_step, number=args.num_warmup_batches)
  File "/opt/anaconda/lib/python3.7/timeit.py", line 232, in timeit
    return Timer(stmt, setup, timer, globals).timeit(number)
  File "/opt/anaconda/lib/python3.7/timeit.py", line 176, in timeit
    timing = self.inner(it, self.timer)
  File "<timeit-src>", line 6, in inner
  File "/usr/local/byteps/example/pytorch/benchmark_bytescheduler.py", line 115, in benchmark_step
    output = model(data)
  File "/opt/anaconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/anaconda/lib/python3.7/site-packages/torchvision/models/resnet.py", line 196, in forward
    x = self.conv1(x)
  File "/opt/anaconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 533, in __call__
    result = hook(self, input)
  File "/opt/anaconda/lib/python3.7/site-packages/byteps-0.1.0-py3.7-linux-x86_64.egg/byteps/bytescheduler/torch/optimizer.py", line 206, in pre_forward_hook
    self._logger.debug("{} {} is ready.".format(self._desc, self._parameter_names[p]))
RuntimeError: bool value of Tensor with more than one value is ambiguous
```

In order to fix this error, you need to replace `self._parameter_names[p]` with `self._parameter_names[id(p)]`.

**Comment by bobzhuyb** [comment]
Thank you! Would you create a pull request to the bytescheduler branch?
