### ISSUE TITLE
install error: error: None of TensorFlow, MXNet, PyTorch plugins were built. See errors above.

### ISSUE THREAD

**Issue by hbsun2113** [bytedance/byteps#145]
Hi, I install byteps by ```python setup.py install``` and meet the following question:
![image](https://user-images.githubusercontent.com/27994442/68834756-73ecb880-06f1-11ea-8693-0b41f79e7a99.png)
I am sure that I have already install Pytorch:
![image](https://user-images.githubusercontent.com/27994442/68834915-dba30380-06f1-11ea-8783-15486af6e1dc.png)
My gcc version is:
![image](https://user-images.githubusercontent.com/27994442/68834856-bca47180-06f1-11ea-8879-4c11a4cbeea9.png)

**Comment by bobzhuyb** [comment]
Hi @hbsun2113, your real error is `cannot find -lnccl_static`. You need to install NCCL before installing BytePS.

**Comment by hbsun2113** [comment]
Hi @bobzhuyb , I have already installed NCCL:
![image](https://user-images.githubusercontent.com/27994442/68857277-6fd69000-071d-11ea-9369-79c534650222.png)
But the problem still here:
![image](https://user-images.githubusercontent.com/27994442/68857466-ca6fec00-071d-11ea-86a4-7870ddcb92c3.png)

**Comment by bobzhuyb** [comment]
@hbsun2113 Can you set the environmental variable BYTEPS_NCCL_HOME to be your NCCL path? See here https://github.com/bytedance/byteps/blob/master/setup.py#L579

**Comment by hbsun2113** [comment]
Thank you @bobzhuyb ! Now I can install it successfully:
![image](https://user-images.githubusercontent.com/27994442/68910614-67b63900-078d-11ea-8db4-48f2297ef19c.png)

But when I referenced [this](https://github.com/bytedance/byteps/blob/master/docs/step-by-step-tutorial.md) to run benchmark task by Pytorch:
![image](https://user-images.githubusercontent.com/27994442/68910796-004cb900-078e-11ea-9ebd-c92427962110.png)

I met the following problem:

BytePS launching worker
running benchmark...
running benchmark...
running benchmark...
running benchmark...
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=383 error=11 : invalid argument
Traceback (most recent call last):
  File "example/pytorch/benchmark_byteps.py", line 110, in <module>
    timeit.timeit(benchmark_step, number=args.num_warmup_batches)
  File "/usr/lib/python2.7/timeit.py", line 237, in timeit
    return Timer(stmt, setup, timer).timeit(number)
  File "/usr/lib/python2.7/timeit.py", line 202, in timeit
    timing = self.inner(it, self.timer)
  File "/usr/lib/python2.7/timeit.py", line 100, in inner
    _func()
  File "example/pytorch/benchmark_byteps.py", line 90, in benchmark_step
    output = model(data)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torchvision/models/resnet.py", line 192, in forward
    x = self.conv1(x)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/conv.py", line 338, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuda runtime error (11) : invalid argument at /pytorch/aten/src/THC/THCGeneral.cpp:383
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=383 error=11 : invalid argument
Traceback (most recent call last):
  File "example/pytorch/benchmark_byteps.py", line 110, in <module>
    timeit.timeit(benchmark_step, number=args.num_warmup_batches)
  File "/usr/lib/python2.7/timeit.py", line 237, in timeit
    return Timer(stmt, setup, timer).timeit(number)
  File "/usr/lib/python2.7/timeit.py", line 202, in timeit
    timing = self.inner(it, self.timer)
  File "/usr/lib/python2.7/timeit.py", line 100, in inner
    _func()
  File "example/pytorch/benchmark_byteps.py", line 90, in benchmark_step
    output = model(data)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torchvision/models/resnet.py", line 192, in forward
    x = self.conv1(x)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/conv.py", line 338, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuda runtime error (11) : invalid argument at /pytorch/aten/src/THC/THCGeneral.cpp:383
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=383 error=11 : invalid argument
Traceback (most recent call last):
  File "example/pytorch/benchmark_byteps.py", line 110, in <module>
    timeit.timeit(benchmark_step, number=args.num_warmup_batches)
  File "/usr/lib/python2.7/timeit.py", line 237, in timeit
    return Timer(stmt, setup, timer).timeit(number)
  File "/usr/lib/python2.7/timeit.py", line 202, in timeit
    timing = self.inner(it, self.timer)
  File "/usr/lib/python2.7/timeit.py", line 100, in inner
    _func()
  File "example/pytorch/benchmark_byteps.py", line 90, in benchmark_step
    output = model(data)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torchvision/models/resnet.py", line 192, in forward
    x = self.conv1(x)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/conv.py", line 338, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuda runtime error (11) : invalid argument at /pytorch/aten/src/THC/THCGeneral.cpp:383
Model: resnet50
Batch size: 32
Number of GPUs: 4
Running warmup...
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=383 error=11 : invalid argument
Traceback (most recent call last):
  File "example/pytorch/benchmark_byteps.py", line 110, in <module>
    timeit.timeit(benchmark_step, number=args.num_warmup_batches)
  File "/usr/lib/python2.7/timeit.py", line 237, in timeit
    return Timer(stmt, setup, timer).timeit(number)
  File "/usr/lib/python2.7/timeit.py", line 202, in timeit
    timing = self.inner(it, self.timer)
  File "/usr/lib/python2.7/timeit.py", line 100, in inner
    _func()
  File "example/pytorch/benchmark_byteps.py", line 90, in benchmark_step
    output = model(data)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torchvision/models/resnet.py", line 192, in forward
    x = self.conv1(x)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/conv.py", line 338, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuda runtime error (11) : invalid argument at /pytorch/aten/src/THC/THCGeneral.cpp:383
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "launcher/launch.py", line 41, in worker
    subprocess.check_call(command, env=my_env, stdout=sys.stdout, stderr=sys.stderr, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command 'example/pytorch/start_pytorch_byteps.sh --model resnet50 --num-iters 1000000' returned non-zero exit status 1

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "launcher/launch.py", line 41, in worker
    subprocess.check_call(command, env=my_env, stdout=sys.stdout, stderr=sys.stderr, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command 'example/pytorch/start_pytorch_byteps.sh --model resnet50 --num-iters 1000000' returned non-zero exit status 1

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "launcher/launch.py", line 41, in worker
    subprocess.check_call(command, env=my_env, stdout=sys.stdout, stderr=sys.stderr, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command 'example/pytorch/start_pytorch_byteps.sh --model resnet50 --num-iters 1000000' returned non-zero exit status 1

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "launcher/launch.py", line 41, in worker
    subprocess.check_call(command, env=my_env, stdout=sys.stdout, stderr=sys.stderr, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command 'example/pytorch/start_pytorch_byteps.sh --model resnet50 --num-iters 1000000' returned non-zero exit status 1

**Comment by bobzhuyb** [comment]
@hbsun2113 It does not look like a BytePS problem to me. The exception is thrown inside forward propagation computation, which has nothing to do with BytePS. You may search solutions to the error `RuntimeError: cuda runtime error (11) : invalid argument at /pytorch/aten/src/THC/THCGeneral.cpp:383`

**Comment by hbsun2113** [comment]
@bobzhuyb You are right and I  install a new PyTorch version by ```pip install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cu101/torch_nightly.html```.
Next, I uninstall byteps by ```pip uninstall byteps```, and install again by ```python setup.py install```.
When I rerun ```python launcher/launch.py example/pytorch/start_pytorch_byteps.sh --model resnet50 --num-iters 1000000```, I met the following question:
BytePS launching worker
running benchmark...
running benchmark...
running benchmark...
running benchmark...
Traceback (most recent call last):
  File "example/pytorch/benchmark_byteps.py", line 9, in <module>
    import byteps.torch as bps
  File "/usr/local/lib/python2.7/dist-packages/byteps-0.1.0-py2.7-linux-x86_64.egg/byteps/torch/__init__.py", line 22, in <module>
    from byteps.torch.ops import push_pull_async_inplace as byteps_push_pull
  File "/usr/local/lib/python2.7/dist-packages/byteps-0.1.0-py2.7-linux-x86_64.egg/byteps/torch/ops.py", line 29, in <module>
    from byteps.torch import c_lib
ImportError: /usr/local/lib/python2.7/dist-packages/byteps-0.1.0-py2.7-linux-x86_64.egg/byteps/torch/c_lib.so: undefined symbol: _ZN6caffe26detail36_typeMetaDataInstance_preallocated_7E
Traceback (most recent call last):
  File "example/pytorch/benchmark_byteps.py", line 9, in <module>
    import byteps.torch as bps
  File "/usr/local/lib/python2.7/dist-packages/byteps-0.1.0-py2.7-linux-x86_64.egg/byteps/torch/__init__.py", line 22, in <module>
    from byteps.torch.ops import push_pull_async_inplace as byteps_push_pull
  File "/usr/local/lib/python2.7/dist-packages/byteps-0.1.0-py2.7-linux-x86_64.egg/byteps/torch/ops.py", line 29, in <module>
    from byteps.torch import c_lib
ImportError: /usr/local/lib/python2.7/dist-packages/byteps-0.1.0-py2.7-linux-x86_64.egg/byteps/torch/c_lib.so: undefined symbol: _ZN6caffe26detail36_typeMetaDataInstance_preallocated_7E
Traceback (most recent call last):
Traceback (most recent call last):
  File "example/pytorch/benchmark_byteps.py", line 9, in <module>
  File "example/pytorch/benchmark_byteps.py", line 9, in <module>
        import byteps.torch as bps
import byteps.torch as bps
  File "/usr/local/lib/python2.7/dist-packages/byteps-0.1.0-py2.7-linux-x86_64.egg/byteps/torch/__init__.py", line 22, in <module>
  File "/usr/local/lib/python2.7/dist-packages/byteps-0.1.0-py2.7-linux-x86_64.egg/byteps/torch/__init__.py", line 22, in <module>
        from byteps.torch.ops import push_pull_async_inplace as byteps_push_pull
from byteps.torch.ops import push_pull_async_inplace as byteps_push_pull
  File "/usr/local/lib/python2.7/dist-packages/byteps-0.1.0-py2.7-linux-x86_64.egg/byteps/torch/ops.py", line 29, in <module>
  File "/usr/local/lib/python2.7/dist-packages/byteps-0.1.0-py2.7-linux-x86_64.egg/byteps/torch/ops.py", line 29, in <module>
    from byteps.torch import c_lib
    ImportErrorfrom byteps.torch import c_lib
: /usr/local/lib/python2.7/dist-packages/byteps-0.1.0-py2.7-linux-x86_64.egg/byteps/torch/c_lib.so: undefined symbol: _ZN6caffe26detail36_typeMetaDataInstance_preallocated_7EImportError
: /usr/local/lib/python2.7/dist-packages/byteps-0.1.0-py2.7-linux-x86_64.egg/byteps/torch/c_lib.so: undefined symbol: _ZN6caffe26detail36_typeMetaDataInstance_preallocated_7E
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "launcher/launch.py", line 41, in worker
    subprocess.check_call(command, env=my_env, stdout=sys.stdout, stderr=sys.stderr, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command 'example/pytorch/start_pytorch_byteps.sh --model resnet50 --num-iters 1000000' returned non-zero exit status 1

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "launcher/launch.py", line 41, in worker
    subprocess.check_call(command, env=my_env, stdout=sys.stdout, stderr=sys.stderr, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command 'example/pytorch/start_pytorch_byteps.sh --model resnet50 --num-iters 1000000' returned non-zero exit status 1

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "launcher/launch.py", line 41, in worker
    subprocess.check_call(command, env=my_env, stdout=sys.stdout, stderr=sys.stderr, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command 'example/pytorch/start_pytorch_byteps.sh --model resnet50 --num-iters 1000000' returned non-zero exit status 1

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "launcher/launch.py", line 41, in worker
    subprocess.check_call(command, env=my_env, stdout=sys.stdout, stderr=sys.stderr, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command 'example/pytorch/start_pytorch_byteps.sh --model resnet50 --num-iters 1000000' returned non-zero exit status 1
  

It seems that byteps is not uninstalled successfully, is it right?

**Comment by hbsun2113** [comment]
Hi, @bobzhuyb . It seems that uninstall byteps by ```pip uninstall byteps``` does not work. 
I do the following work:
1. delete the repo 
2. git clone again 
3. run the cmd ```python setup.py install``` again
Now it works, I wonder why ```pip uninstall byteps``` does not work?

**Comment by bobzhuyb** [comment]
@hbsun2113 Sorry for not replying earlier. You can refer to this post on how to uninstall byteps --
https://github.com/bytedance/byteps/issues/28#issuecomment-507010629

You need to clean the repo (just like `make clean` after `make uninstall` when you build common C++ code). Otherwise, the C++ part of byteps may still be linked against the older PyTorch lib.

**Comment by hbsun2113** [comment]
@bobzhuyb  I got it. THX!
