### ISSUE TITLE
gradient registry has no entry for: BytepsPushPull

### ISSUE THREAD

**Issue by wstian** [bytedance/byteps#149]
**Describe the bug**
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gradients_impl.py", line 768, in _GradientsHelper
    grad_fn = ops.get_gradient_function(op)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 2462, in get_gradient_function
    return _gradient_registry.lookup(op_type)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/registry.py", line 93, in lookup
    "%s registry has no entry for: %s" % (self._name, name))
LookupError: gradient registry has no entry for: BytepsPushPull

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/wangst/liteng_face_tf/train_nets_bps.py", line 417, in <module>
    main()
  File "/w/train.py", line 30, in main
    grads = opt.compute_gradients(loss)
  File "/w/train.py", line 591, in compute_gradients
    gradients = self._optimizer.compute_gradients(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/optimizer.py", line 519, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gradients_impl.py", line 630, in gradients
    gate_gradients, aggregation_method, stop_gradients)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gradients_impl.py", line 772, in _GradientsHelper
    (op.name, op.type))
LookupError: No gradient defined for operation 'BytePSPushPull_merged_net_0' (op type: BytepsPushPull)
```

**To Reproduce**
1. define push_pull op for a Tensor
```python
    merged_embedding = tf.concat(axis=0, values=embedding_values, name='merged_embedding')
    merged_embedding_pulled = bps.push_pull(merged_embedding, average=False)
```

2 the program fail when `opt.compute_gradient()`

**Expected behavior**
no error

**Screenshots**

**Environment (please complete the following information):**
 - OS: ubuntu
 - GCC version:
 - CUDA and NCCL version: 2.4.2-1+cuda9.0
 - Framework (TF, PyTorch, MXNet): TF

**Additional context**

**Comment by ymjiang** [comment]
Thank you for your contribution! We will review the PR soon.
