### ISSUE TITLE
undefined symbol during import

### ISSUE THREAD

**Issue by eric-haibin-lin** [bytedance/byteps#173]
**Describe the bug**
BytePS version: 3ef385ae3b 

**To Reproduce**
1. See error below

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: Linux
 - GCC version: gcc (Ubuntu 4.9.3-13ubuntu2) 4.9.3
 - CUDA and NCCL version: Cuda compilation tools, release 10.0, V10.0.130 
 - Framework (TF, PyTorch, MXNet): mxnet-cu100     1.6.0b20191102 

**Additional context**
```
root@efa48d493056:/# python3 -c 'import byteps.mxnet'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/byteps/mxnet/__init__.py", line 25, in <module>
    from byteps.mxnet.ops import byteps_push_pull, byteps_declare_tensor
  File "/usr/local/lib/python3.5/dist-packages/byteps/mxnet/ops.py", line 30, in <module>
    _basics = _BytePSBasics(__file__, 'c_lib')
  File "/usr/local/lib/python3.5/dist-packages/byteps/common/__init__.py", line 57, in __init__
    self.C_LIB_CTYPES = ctypes.CDLL(full_path, mode=ctypes.RTLD_GLOBAL)
  File "/usr/lib/python3.5/ctypes/__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/python3.5/dist-packages/byteps/mxnet/c_lib.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZN5mxnet7Storage13_GetSharedRefEv

```

**Comment by bobzhuyb** [comment]
Thanks Haibin. For other's reference, MXNet 1.6 breaks the current BytePS build. It'll be fixed by Haibin's PR.

**Comment by bobzhuyb** [comment]
Merged. Thanks for the contribution!
