### ISSUE TITLE
tests/test_mxnet.py Failed

### ISSUE THREAD

**Issue by ChaokunChang** [bytedance/byteps#193]
**Describe the bug**
I am running the tests/test_mxnet.py in Amazon p2 instance, but the test failed. 
The output of "TEST_TYPE=mxnet bash tests/run_byteps_test.sh" is:
`
TEST MXNET ...
BytePS launching worker
[01:33:10] /home/ubuntu/incubator-mxnet/src/base.cc:84: Upgrade advisory: this mxnet has been built against cuDNN lib version 7501, which is older than the oldest version tested by CI (7600).  Set MXNET_CUDNN_LIB_CHECKING=0 to quiet this warning.
[01:33:10] /home/ubuntu/incubator-mxnet/src/base.cc:84: Upgrade advisory: this mxnet has been built against cuDNN lib version 7501, which is older than the oldest version tested by CI (7600).  Set MXNET_CUDNN_LIB_CHECKING=0 to quiet this warning.
[01:33:10] /home/ubuntu/incubator-mxnet/src/base.cc:84: Upgrade advisory: this mxnet has been built against cuDNN lib version 7501, which is older than the oldest version tested by CI (7600).  Set MXNET_CUDNN_LIB_CHECKING=0 to quiet this warning.
[01:33:10] /home/ubuntu/incubator-mxnet/src/base.cc:84: Upgrade advisory: this mxnet has been built against cuDNN lib version 7501, which is older than the oldest version tested by CI (7600).  Set MXNET_CUDNN_LIB_CHECKING=0 to quiet this warning.
tensor before push_pull: 
[-88.276085    9.469676  -28.467728   32.062294  -16.11681   -62.981438
  83.053955   19.23256    15.465963   89.03272    44.934155   -7.217002
  57.025764  -39.45068    89.96457   -55.9767      7.7130795]
<NDArray 17 @gpu(0)>

Segmentation fault: 11

Segmentation fault: 11

tensor before push_pull: 
[ 21.069908 -94.97407   85.203156  52.046513  49.008537 -40.987206
  72.30864   71.563705 -17.39539  -54.30231  -87.22985   56.130363
  96.28754   70.68246   56.345104  27.549076 -98.324036]
<NDArray 17 @gpu(2)>

Segmentation fault: 11

Segmentation fault: 11

tensor before push_pull: 
[ 13.224661     0.13791323 -88.42125     25.27721     13.318825
  75.00076     74.871086   -56.566643   -52.70393     -7.9426765
 -81.11471    -57.324112    42.22908     79.71407     18.322575
   6.675613    56.61081   ]
<NDArray 17 @gpu(1)>

Segmentation fault: 11

Segmentation fault: 11

tensor before push_pull: 
[ 44.921947  -22.404182   19.133305   13.094497   11.725103  -69.86146
   0.1105547  33.98166    92.52082   -85.41071    16.735744   24.991835
 -77.336075   14.822626   25.756227   43.89869    58.843494 ]
<NDArray 17 @gpu(3)>

Segmentation fault: 11

Segmentation fault: 11

Segmentation fault (core dumped)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/ubuntu/anaconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/byteps/launcher/launch.py", line 47, in worker
    subprocess.check_call(command, env=my_env, stdout=sys.stdout, stderr=sys.stderr, shell=True)
  File "/home/ubuntu/anaconda3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'python3 tests/test_mxnet.py' returned non-zero exit status 139.

Exception in thread Thread-4:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/ubuntu/anaconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/byteps/launcher/launch.py", line 47, in worker
    subprocess.check_call(command, env=my_env, stdout=sys.stdout, stderr=sys.stderr, shell=True)
  File "/home/ubuntu/anaconda3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'python3 tests/test_mxnet.py' returned non-zero exit status 255.

Segmentation fault (core dumped)
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/ubuntu/anaconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/byteps/launcher/launch.py", line 47, in worker
    subprocess.check_call(command, env=my_env, stdout=sys.stdout, stderr=sys.stderr, shell=True)
  File "/home/ubuntu/anaconda3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'python3 tests/test_mxnet.py' returned non-zero exit status 139.

Segmentation fault (core dumped)
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/ubuntu/anaconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/byteps/launcher/launch.py", line 47, in worker
    subprocess.check_call(command, env=my_env, stdout=sys.stdout, stderr=sys.stderr, shell=True)
  File "/home/ubuntu/anaconda3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'python3 tests/test_mxnet.py' returned non-zero exit status 139.
`

**To Reproduce**
1. git clone --recurse-submodules https://github.com/bytedance/byteps
2. cd byteps; python setup.py install
3. TEST_TYPE=mxnet bash tests/run_byteps_test.sh 

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: Linux version 4.15.0-1057-aws (buildd@lgw01-amd64-030) (gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)) #59-Ubuntu SMP Wed Dec 4 10:02:00 UTC 201
 - GCC version: gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1) 
 - CUDA and NCCL version: CUDA Version 10.0.130
 - Framework (TF, PyTorch, MXNet): MXNET

**Additional context**

**Comment by bobzhuyb** [comment]
Would you set `BYTEPS_ENABLE_GDB=1` and try again? We would recommend that you start with our docker images, so that we can isolate the environment problems like the GCC version.

**Comment by ChaokunChang** [comment]
Still not OK. 

ubuntu@xxxxx:~/byteps/tests$ TEST_TYPE=mxnet bash run_byteps_test.sh 
TEST MXNET ...
BytePS launching worker
/bin/sh: 1: gdb: not found
/bin/sh: 1: gdb: not found
/bin/sh: 1: gdb: not found
/bin/sh: 1: gdb: not found
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/ubuntu/anaconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/byteps/launcher/launch.py", line 47, in worker
    subprocess.check_call(command, env=my_env, stdout=sys.stdout, stderr=sys.stderr, shell=True)
  File "/home/ubuntu/anaconda3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'gdb -ex 'run' -ex 'bt' -batch --args python3 ./test_mxnet.py' returned non-zero exit status 127.

Exception in thread Thread-4:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/ubuntu/anaconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/byteps/launcher/launch.py", line 47, in worker
    subprocess.check_call(command, env=my_env, stdout=sys.stdout, stderr=sys.stderr, shell=True)
  File "/home/ubuntu/anaconda3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'gdb -ex 'run' -ex 'bt' -batch --args python3 ./test_mxnet.py' returned non-zero exit status 127.

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/ubuntu/anaconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/byteps/launcher/launch.py", line 47, in worker
    subprocess.check_call(command, env=my_env, stdout=sys.stdout, stderr=sys.stderr, shell=True)
  File "/home/ubuntu/anaconda3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'gdb -ex 'run' -ex 'bt' -batch --args python3 ./test_mxnet.py' returned non-zero exit status 127.

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/ubuntu/anaconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/byteps/launcher/launch.py", line 47, in worker
    subprocess.check_call(command, env=my_env, stdout=sys.stdout, stderr=sys.stderr, shell=True)
  File "/home/ubuntu/anaconda3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'gdb -ex 'run' -ex 'bt' -batch --args python3 ./test_mxnet.py' returned non-zero exit status 127.

**Comment by zhongyuchen** [comment]
@ChaokunChang  I think you should `apt-get install gdb` in your docker first.

**Comment by ChaokunChang** [comment]
Yes... Thank you for pointing out. 
Then the output became :
`
TEST MXNET ...
BytePS launching worker

[1]+  Stopped                 TEST_TYPE=mxnet bash tests/run_byteps_test.sh
`
What should I do next?

**Comment by zhongyuchen** [comment]
@ChaokunChang  I can pass those tests. Did you start your server and scheduler?
```
TEST MXNET ...
BytePS launching worker
tensor before push_pull: 
[ 21.069908 -94.97407   85.203156  52.046513  49.008537 -40.987206
  72.30864   71.563705 -17.39539  -54.30231  -87.22985   56.130363
  96.28754   70.68246   56.345104  27.549076 -98.324036]
<NDArray 17 @gpu(2)>
tensor after push_pull: 
[ -2.2648907 -26.942665   -3.1381292  30.620129   14.483914  -24.707336
  57.58606    17.05282     9.471867  -14.655745  -26.668665    4.1452713
  29.551579   31.442118   47.59712     5.5366697   6.2108374]
<NDArray 17 @gpu(2)>
test_byteps_push_pull passed
test_byteps_trainer_param_order passed
test_byteps_push_pull_inplace passed
tensor before push_pull: 
[-88.276085    9.469676  -28.467728   32.062294  -16.11681   -62.981438
  83.053955   19.23256    15.465963   89.03272    44.934155   -7.217002
  57.025764  -39.45068    89.96457   -55.9767      7.7130795]
<NDArray 17 @gpu(0)>
tensor after push_pull: 
[ -2.2648907 -26.942665   -3.1381292  30.620129   14.483914  -24.707336
  57.58606    17.05282     9.471867  -14.655745  -26.668665    4.1452713
  29.551579   31.442118   47.59712     5.5366697   6.2108374]
<NDArray 17 @gpu(0)>
test_byteps_push_pull passed
test_byteps_trainer_param_order passed
test_byteps_push_pull_inplace passed
tensor before push_pull: 
[ 44.921947  -22.404182   19.133305   13.094497   11.725103  -69.86146
   0.1105547  33.98166    92.52082   -85.41071    16.735744   24.991835
 -77.336075   14.822626   25.756227   43.89869    58.843494 ]
<NDArray 17 @gpu(3)>
tensor after push_pull: 
[ -2.2648907 -26.942665   -3.1381292  30.620129   14.483914  -24.707336
  57.58606    17.05282     9.471867  -14.655745  -26.668665    4.1452713
  29.551579   31.442118   47.59712     5.5366697   6.2108374]
<NDArray 17 @gpu(3)>
test_byteps_push_pull passed
test_byteps_trainer_param_order passed
test_byteps_push_pull_inplace passed
tensor before push_pull: 
[ 13.224661     0.13791323 -88.42125     25.27721     13.318825
  75.00076     74.871086   -56.566643   -52.70393     -7.9426765
 -81.11471    -57.324112    42.22908     79.71407     18.322575
   6.675613    56.61081   ]
<NDArray 17 @gpu(1)>
tensor after push_pull: 
[ -2.2648907 -26.942665   -3.1381292  30.620129   14.483914  -24.707336
  57.58606    17.05282     9.471867  -14.655745  -26.668665    4.1452713
  29.551579   31.442118   47.59712     5.5366697   6.2108374]
<NDArray 17 @gpu(1)>
test_byteps_push_pull passed
test_byteps_trainer_param_order passed
test_byteps_push_pull_inplace passed
```
