### ISSUE TITLE
tensorflow pull is not overlapped with computation

### ISSUE THREAD

**Issue by hyungjun2** [bytedance/byteps#286]
**Describe the bug**
I profiled the tensorflow example using resnet50.  It does not overlap with forward computation.
And when using byteschduler, an error message appears indicating that the kernel is not registered.
An error occurred when using byteschduler's make, so the make file was modified.

modified make command
g++ -std=c++11 -shared -D_GLIBCXX_USE_CXX11_ABI=0 -o libplugin.so plugin.cc ${TF_CFLAGS[@]} -fPIC ${TF_LFLAGS[@]} 

byteps command
export BYTEPS_SERVER_ENABLE_SCHEDULE=1
export DMLC_NUM_WORKER=2
export DMLC_ROLE=scheduler
export DMLC_NUM_SERVER=1
export DMLC_PS_ROOT_URI=10.0.0.1 # the scheduler IP
export DMLC_PS_ROOT_PORT=1234  # the scheduler port
export DMLC_NODE_HOST=10.0.0.1
bpslaunch

export DMLC_NUM_WORKER=2
export DMLC_ROLE=server
export DMLC_NUM_SERVER=1
export DMLC_PS_ROOT_URI=10.0.0.1 # the scheduler IP
export DMLC_PS_ROOT_PORT=1234  # the scheduler port
export DMLC_NODE_HOST=10.0.0.1
bpslaunch

export NVIDIA_VISIBLE_DEVICES=0
export DMLC_WORKER_ID=0
export DMLC_NUM_WORKER=2
export DMLC_ROLE=worker
export DMLC_NUM_SERVER=1
export DMLC_PS_ROOT_URI=10.0.0.1 # the scheduler IP
export DMLC_PS_ROOT_PORT=1234 # the scheduler port
export DMLC_NODE_HOST=10.0.0.3
bpslaunch nvprof -fo aaa.nvvp python synthetic_benchmark.py --model ResNet50 --num-iters 20

export NVIDIA_VISIBLE_DEVICES=0
export DMLC_WORKER_ID=1
export DMLC_NUM_WORKER=2
export DMLC_ROLE=worker
export DMLC_NUM_SERVER=1
export DMLC_PS_ROOT_URI=10.0.0.1 # the scheduler IP
export DMLC_PS_ROOT_PORT=1234 # the scheduler port
export DMLC_NODE_HOST=10.0.0.4
bpslaunch nvprof -fo aaa.nvvp python synthetic_benchmark.py --model ResNet50 --num-iters 20

------------------
byteschduler command

PS
python ../tf_cnn_benchmarks.py \
--model=alexnet \
--num_batches=100 \
--train_dir=../train_model \
--batch_size=32 \
--optimizer=sgd \
--data_name=cifar10 \
--data_dir=../cifar-10-batches-py \
--variable_update=parameter_server \
--job_name=worker \
--ps_hosts=10.0.0.3:50000 \
--worker_hosts=10.0.0.1:50001 \
--task_index=0

WORKER
python ../tf_cnn_benchmarks.py \
--model=alexnet \
--num_batches=100 \
--train_dir=../train_model \
--batch_size=32 \
--optimizer=sgd \
--data_name=cifar10 \
--data_dir=../cifar-10-batches-py \
--variable_update=parameter_server \
--job_name=ps \
--ps_hosts=10.0.0.3:50000 \
--worker_hosts=10.0.0.1:50001 \
--task_index=0

ByteScheduler ERR message

2020-08-12 14:54:45.935772: I plugin.cc:721] ByteScheduler taking over gradient tower_0/v/gradients/AddN_1
2020-08-12 14:54:45.935877: I plugin.cc:721] ByteScheduler taking over gradient tower_0/v/gradients/AddN
2020-08-12 14:54:45.935935: I plugin.cc:721] ByteScheduler taking over gradient tower_0/v/gradients/AddN_3
2020-08-12 14:54:45.935997: I plugin.cc:721] ByteScheduler taking over gradient tower_0/v/gradients/AddN_2
2020-08-12 14:54:45.936053: I plugin.cc:721] ByteScheduler taking over gradient tower_0/v/gradients/AddN_4
2020-08-12 14:54:45.936108: I plugin.cc:721] ByteScheduler taking over gradient tower_0/v/gradients/AddN_14
2020-08-12 14:54:45.936161: I plugin.cc:721] ByteScheduler taking over gradient tower_0/v/gradients/AddN_13
2020-08-12 14:54:45.936212: I plugin.cc:721] ByteScheduler taking over gradient tower_0/v/gradients/AddN_12
2020-08-12 14:54:45.936265: I plugin.cc:721] ByteScheduler taking over gradient tower_0/v/gradients/AddN_11
2020-08-12 14:54:45.936317: I plugin.cc:721] ByteScheduler taking over gradient tower_0/v/gradients/AddN_10
2020-08-12 14:54:45.936368: I plugin.cc:721] ByteScheduler taking over gradient tower_0/v/gradients/AddN_9
2020-08-12 14:54:45.936419: I plugin.cc:721] ByteScheduler taking over gradient tower_0/v/gradients/AddN_8
2020-08-12 14:54:45.936470: I plugin.cc:721] ByteScheduler taking over gradient tower_0/v/gradients/AddN_7
2020-08-12 14:54:45.936521: I plugin.cc:721] ByteScheduler taking over gradient tower_0/v/gradients/AddN_17
2020-08-12 14:54:45.936576: I plugin.cc:721] ByteScheduler taking over gradient tower_0/v/gradients/AddN_16
2020-08-12 14:54:45.936628: I plugin.cc:721] ByteScheduler taking over gradient tower_0/v/gradients/AddN_15
2020-08-12 14:54:45.936679: I plugin.cc:721] ByteScheduler taking over gradient tower_0/v/gradients/AddN_6
2020-08-12 14:54:45.936731: I plugin.cc:721] ByteScheduler taking over gradient tower_0/v/gradients/AddN_5
2020-08-12 14:54:45.936783: I plugin.cc:721] ByteScheduler taking over gradient tower_0/v/gradients/AddN_19
2020-08-12 14:54:45.936834: I plugin.cc:721] ByteScheduler taking over gradient tower_0/v/gradients/AddN_18
2020-08-12 14:54:45.936888: I plugin.cc:721] ByteScheduler taking over gradient tower_0/v/gradients/AddN_21
2020-08-12 14:54:45.936940: I plugin.cc:721] ByteScheduler taking over gradient tower_0/v/gradients/AddN_20
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.NotFoundError'>, No registered 'RecvApplyGradientDescent' OpKernel for GPU devices compatible with node node append_apply_gradient_ops/GradientDescent/update_v/cg/conv0/biases/ApplyGradientDescent (defined at /byte_schduler/benchmarks/scripts/tf_cnn_benchmarks/variable_mgr.py:107)  = RecvApplyGradientDescent[T=DT_FLOAT, recv_device="/job:ps/replica:0/task:0/device:GPU:0", send_device="/job:worker/replica:0/task:0/device:GPU:0", send_device_incarnation=-826861059828087564, tensor_name="edge_400_tower_0/v/gradients/AddN_20", variable_name="v/cg/conv0/biases"](v/cg/conv0/biases, learning_rate/ExponentialDecay_S57)
	.  Registered:  device='CPU'; T in [DT_FLOAT]

	 [[node append_apply_gradient_ops/GradientDescent/update_v/cg/conv0/biases/ApplyGradientDescent (defined at /byte_schduler/benchmarks/scripts/tf_cnn_benchmarks/variable_mgr.py:107)  = RecvApplyGradientDescent[T=DT_FLOAT, recv_device="/job:ps/replica:0/task:0/device:GPU:0", send_device="/job:worker/replica:0/task:0/device:GPU:0", send_device_incarnation=-826861059828087564, tensor_name="edge_400_tower_0/v/gradients/AddN_20", variable_name="v/cg/conv0/biases"](v/cg/conv0/biases, learning_rate/ExponentialDecay_S57)]]

An error occurred when using the provided make file
Traceback (most recent call last):
  File "/byte_schduler/benchmarks/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py", line 32, in <module>
    tf.load_library('/byte_schduler/byteps/bytescheduler/bytescheduler/tensorflow/libplugin.so')
  File "/lib/python3.5/site-packages/tensorflow/python/framework/load_library.py", line 158, in load_library
    py_tf.TF_LoadLibrary(lib)
tensorflow.python.framework.errors_impl.NotFoundError: /byte_schduler/byteps/bytescheduler/bytescheduler/tensorflow/libplugin.so: undefined symbol: _ZTIN10tensorflow8OpKernelE

**Expected behavior**
If it overlaps with forward computation, it seems that HtoD should be above the forward operation, but it is not visible.
Should I use a bytescheduler branch to overlap with forward in tensorflow?

**Screenshots**
![ttt](https://user-images.githubusercontent.com/29619476/89865506-d32c1a80-dbe8-11ea-85a6-6bce133aef01.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 16.04.6 LTS
 - GCC version: 5.4.0
 - CUDA and NCCL version: 9, 1.3 / 10.0 1.3
 - Framework (TF, PyTorch, MXNet): TF 1.12 / TF 1.13 (cnn_tf_v1.13_compatible)

**Comment by ymjiang** [comment]
The TF `synthetic_benchmark.py` example you run does not support overlapping between forward propagation and communication. So the problem is expected. Yes, you should use the bytescheduler branch if you want to break the barrier. 

Ping @pengyanghua: Can you please check the bytescheduler problem?

**Comment by hyungjun2** [comment]
thank you for the reply

I solved the No registered problem using the command below. However, a new problem arose.

PS command

CUDA_VISIBLE_DEVICES= python /home/jun/horovod_test/byte_schduler/benchmarks/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py \
--model=alexnet \
--num_batches=100 \
--train_dir=/home/jun/horovod_test/byte_schduler/train_model \
--batch_size=32 \
--optimizer=sgd \
--data_name=cifar10 \
--data_dir=/home/jun/horovod_test/byte_schduler/data/cifar-10-batches-py \
--variable_update=parameter_server \
--job_name=ps \
--ps_hosts=10.0.0.3:50000 \
--worker_hosts=10.0.0.1:50001 \
--task_index=0 \
--device=cpu \
--mkl=True

On the second iteration, the error message below is displayed and it hangs.
Is there any way to do debugging?

https://github.com/bytedance/byteps/blob/78ae602da8fdb2ccb3ee666933d6e791102de355/bytescheduler/bytescheduler/tensorflow/plugin.cc#L211

2020-08-13 13:16:05.676160: W plugin.cc:211] Aborted: Cleanup 34329971863202606
2020-08-13 13:16:05.676279: W plugin.cc:211] Aborted: Cleanup 34329971863202606
2020-08-13 13:16:05.676319: W plugin.cc:211] Aborted: Cleanup 34329971863202606

**Comment by pengyanghua** [comment]
@hyungjun2 Did you apply the [patch](https://github.com/bytedance/byteps/blob/78ae602da8fdb2ccb3ee666933d6e791102de355/bytescheduler/bytescheduler/tensorflow/tf.patch) and recompile TF 1.13 from source code?

**Comment by hyungjun2** [comment]
@pengyanghua  
Yes i did

![diff_img](https://user-images.githubusercontent.com/29619476/90350410-0999e780-e078-11ea-8ce3-e5a2bcad8eee.png)

**Comment by pengyanghua** [comment]
@hyungjun2  Thanks for your confirmation. We did not test the new cnn_tf_v1.13_compatible branch. I will try it to see if the bug can be reproduced.

**Comment by lucasleesw** [comment]
Could you share how to implement bytescheduler with overlapping between forward propagation and communication?
Is Byteps necessary? Tensorflow parts docs of bytescheduler might be confused.
Any information help, thank you a lot~

**Comment by pengyanghua** [comment]
@lucasleesw You may check the overlapping implementation here https://github.com/bytedance/byteps/blob/bytescheduler/bytescheduler/bytescheduler/tensorflow/plugin.cc, the computation dependency graph is modified. BytePS is not necessary.

**Comment by pengyanghua** [comment]
@lucasleesw Also, to observe the overlapping from timeline, it is recommended to profile large models like VGG.
