### ISSUE TITLE
Failure in distributed training with MXNet

### ISSUE THREAD

**Issue by juncgu** [bytedance/byteps#34]
**Describe the bug**
Hi,
I am following [this note](https://github.com/bytedance/byteps/blob/master/docs/step-by-step-tutorial.md#distributed-training) and want to run distributed training using `byteps` in 
`MXNet`. Both `MXNet` ([bytedance/incubator-mxnet](https://github.com/bytedance/incubator-mxnet/tree/fb2889e486c5ae3f84411cfb6ceb907f663bfe9e)) and `byteps` (cb88d29a8cc5ef6cec70f3bd6cb7c87b38fcbd37) are built from their source code with RDMA enabled (`USE_RDMA=1`). The basic test for mxnet ([tests/test_mxnet.py](https://github.com/bytedance/byteps/blob/master/tests/test_mxnet.py)) with single worker has been passed in this environment.

However, when I am running the [benchmark for `MXNet`](https://github.com/bytedance/byteps/blob/master/docs/step-by-step-tutorial.md#distributed-training), it keeps crashing and reports the following error:
> mxnet.base.MXNetError: [00:05:18] src/storage/./pinned_memory_storage.h:61: Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading CUDA: all CUDA-capable devices are busy or unavailable

I have one scheduler, one server, and one worker (with 4 GPUs) in my experiment. The scheduler and the server are sharing the same node, and the worker is running on another node. All of them are running in their own 'virtualenv' without using the dockfile in this repo.

More details can be found in the followings.

**To Reproduce**
* scheduler
```bash
export DMLC_ENABLE_RDMA=1
export DMLC_INTERFACE='ib0'
export DMLC_PS_ROOT_URI='192.168.0.103'
export DMLC_PS_ROOT_PORT=40001
export BYTEPS_FORCE_DISTRIBUTED=1
export DMLC_NUM_SERVER=1
export DMLC_NUM_WORKER=1
export DMLC_ROLE='scheduler'
python /{byteps_root}/launcher/launch.py
```
* server
```bash
export DMLC_ENABLE_RDMA=1
export DMLC_INTERFACE='ib0'
export DMLC_PS_ROOT_URI='192.168.0.103'
export DMLC_PS_ROOT_PORT=40001
export BYTEPS_FORCE_DISTRIBUTED=1
export DMLC_NUM_SERVER=1
export DMLC_NUM_WORKER=1
export DMLC_ROLE='server'
python /{byteps_root}/launcher/launch.py
```
* worker-0
```bash
export DMLC_ENABLE_RDMA=1
export DMLC_INTERFACE='ib0'
export DMLC_PS_ROOT_URI='192.168.0.103'
export DMLC_PS_ROOT_PORT=40001
export BYTEPS_FORCE_DISTRIBUTED=1
export DMLC_NUM_SERVER=1
export DMLC_NUM_WORKER=1
export DMLC_ROLE='worker'
export EVAL_TYPE=benchmark 
export DMLC_WORKER_ID=0
export NVIDIA_VISIBLE_DEVICES=0,1,2,3

python /{byteps_root}/launcher/launch.py /{byteps_root}/example/mxnet/start_mxnet_byteps.sh --benchmark 1 --batch-size=32
```
After launching them, I can see they are building RDMA connections and are executing `ADD_NODE`. However, the worker will also report the following errors:
```text
...
[01:19:44] src/./rdma_van.h:572: Connecting to W[9]
[01:19:44] src/van.cc:306: W[9] is connected to others
INFO:root:start with arguments Namespace(batch_size=32, benchmark=1, cpu_train=False, data_nthreads=4, data_train=None, data_train_idx='', data_val=None, data_val_idx='', disp_batches=20, dtype='float32', gc_threshold=0.5, gc_type='none', image_shape='3,224,224', initializer='default', kv_store='device', load_epoc$
=None, loss='', lr=0.1, lr_factor=0.1, lr_step_epochs='30,60', macrobatch_size=0, max_random_aspect_ratio=0.25, max_random_h=36, max_random_l=50, max_random_rotate_angle=10, max_random_s=50, max_random_scale=1, max_random_shear_ratio=0.1, min_random_scale=1, model_prefix=None, mom=0.9, monitor=0, network='resnet',
num_classes=1000, num_epochs=80, num_examples=1281167, num_layers=50, optimizer='sgd', pad_size=0, random_crop=1, random_mirror=1, rgb_mean='123.68,116.779,103.939', test_io=0, top_k=0, warmup_epochs=5, warmup_strategy='linear', wd=0.0001)
INFO:root:start with arguments Namespace(batch_size=32, benchmark=1, cpu_train=False, data_nthreads=4, data_train=None, data_train_idx='', data_val=None, data_val_idx='', disp_batches=20, dtype='float32', gc_threshold=0.5, gc_type='none', image_shape='3,224,224', initializer='default', kv_store='device', load_epoc$
=None, loss='', lr=0.1, lr_factor=0.1, lr_step_epochs='30,60', macrobatch_size=0, max_random_aspect_ratio=0.25, max_random_h=36, max_random_l=50, max_random_rotate_angle=10, max_random_s=50, max_random_scale=1, max_random_shear_ratio=0.1, min_random_scale=1, model_prefix=None, mom=0.9, monitor=0, network='resnet',
num_classes=1000, num_epochs=80, num_examples=1281167, num_layers=50, optimizer='sgd', pad_size=0, random_crop=1, random_mirror=1, rgb_mean='123.68,116.779,103.939', test_io=0, top_k=0, warmup_epochs=5, warmup_strategy='linear', wd=0.0001)
INFO:root:start with arguments Namespace(batch_size=32, benchmark=1, cpu_train=False, data_nthreads=4, data_train=None, data_train_idx='', data_val=None, data_val_idx='', disp_batches=20, dtype='float32', gc_threshold=0.5, gc_type='none', image_shape='3,224,224', initializer='default', kv_store='device', load_epoc$
=None, loss='', lr=0.1, lr_factor=0.1, lr_step_epochs='30,60', macrobatch_size=0, max_random_aspect_ratio=0.25, max_random_h=36, max_random_l=50, max_random_rotate_angle=10, max_random_s=50, max_random_scale=1, max_random_shear_ratio=0.1, min_random_scale=1, model_prefix=None, mom=0.9, monitor=0, network='resnet',
num_classes=1000, num_epochs=80, num_examples=1281167, num_layers=50, optimizer='sgd', pad_size=0, random_crop=1, random_mirror=1, rgb_mean='123.68,116.779,103.939', test_io=0, top_k=0, warmup_epochs=5, warmup_strategy='linear', wd=0.0001)
INFO:root:start with arguments Namespace(batch_size=32, benchmark=1, cpu_train=False, data_nthreads=4, data_train=None, data_train_idx='', data_val=None, data_val_idx='', disp_batches=20, dtype='float32', gc_threshold=0.5, gc_type='none', image_shape='3,224,224', initializer='default', kv_store='device', load_epoc$
=None, loss='', lr=0.1, lr_factor=0.1, lr_step_epochs='30,60', macrobatch_size=0, max_random_aspect_ratio=0.25, max_random_h=36, max_random_l=50, max_random_rotate_angle=10, max_random_s=50, max_random_scale=1, max_random_shear_ratio=0.1, min_random_scale=1, model_prefix=None, mom=0.9, monitor=0, network='resnet',
num_classes=1000, num_epochs=80, num_examples=1281167, num_layers=50, optimizer='sgd', pad_size=0, random_crop=1, random_mirror=1, rgb_mean='123.68,116.779,103.939', test_io=0, top_k=0, warmup_epochs=5, warmup_strategy='linear', wd=0.0001)
Traceback (most recent call last):
  File "/{byteps-root}/example/mxnet/train_imagenet_byteps.py", line 66, in <module>
    fit.fit(args, sym, data.get_rec_iter)
  File "/{byteps-root}/example/mxnet/common/fit_byteps.py", line 161, in fit
    (train, val) = data_loader(args, (bps.rank(), bps.size()))
  File "/{byteps-root}/example/mxnet/common/data_byteps.py", line 116, in get_rec_iter
    args.num_examples / args.batch_size, np.float32)
  File "/{byteps-root}/example/mxnet/common/data_byteps.py", line 85, in __init__
    self.data = mx.nd.array(data, dtype=self.dtype, ctx=mx.Context('cpu_pinned', 0))
  File "/{virtualenv-path}/lib/python3.6/site-packages/mxnet-1.5.0-py3.6.egg/mxnet/ndarray/utils.py", line 146, in array
    return _array(source_array, ctx=ctx, dtype=dtype)
  File "/{virtualenv-path}/lib/python3.6/site-packages/mxnet-1.5.0-py3.6.egg/mxnet/ndarray/ndarray.py", line 2503, in array
    arr = empty(source_array.shape, ctx, dtype)
  File "/{virtualenv-path}/lib/python3.6/site-packages/mxnet-1.5.0-py3.6.egg/mxnet/ndarray/ndarray.py", line 3892, in empty
    return NDArray(handle=_new_alloc_handle(shape, ctx, False, dtype))
  File "/{virtualenv-path}/lib/python3.6/site-packages/mxnet-1.5.0-py3.6.egg/mxnet/ndarray/ndarray.py", line 140, in _new_alloc_handle
Traceback (most recent call last):
  File "/{byteps-root}/example/mxnet/train_imagenet_byteps.py", line 66, in <module>
    ctypes.byref(hdl)))
  File "/{virtualenv-path}/lib/python3.6/site-packages/mxnet-1.5.0-py3.6.egg/mxnet/base.py", line 252, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [01:19:45] src/storage/./pinned_memory_storage.h:61: Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading CUDA: all CUDA-capable devices are busy or unavailable
...
```
However, if the worker only has one GPU like this:
```bash
export NVIDIA_VISIBLE_DEVICES=0
```
then, **the example can run without any problems**.

It seems like one worker subprocess (in `launch.py`) is trying to get some busy GPUs when allocating `NDArray`. Did I make any mistakes or missing any configurations during this experiment?

Thank you

**Expected behavior**
None
**Screenshots**
None

**Environment (please complete the following information):**
 - OS: RedHat 7.5 (on PowerPC ppc64le)
 - GCC version: 5.4.0
 - Python version: 3.6.2 anaconda
 - CUDA and NCCL version: 9.2
 - Framework : MXNet

**Additional context**
None

**Comment by bobzhuyb** [comment]
@juncgu We have seen this before. This is due to your GCC version... For MXNet, you need to use GCC 4.9. Refer to this https://github.com/bytedance/byteps/blob/master/docker/Dockerfile.worker.mxnet.cu100#L113 about how you can pin GCC to 4.9

**Comment by bobzhuyb** [comment]
By the way, PowerPC is completely untested.

**Comment by flynnamy** [comment]
@juncgu Could you please test pytorch scripts?

**Comment by bobzhuyb** [comment]
@juncgu I read your log again, and saw this 
```
self.data = mx.nd.array(data, dtype=self.dtype, ctx=mx.Context('cpu_pinned', 0))
```

It's allocating memory on CPUs, and (I guess) trying to pinned it using calls like cudaHostRegister but failed. Is there a limitation of pinned memory on PowerPC?

**Comment by juncgu** [comment]
Thanks, @bobzhuyb.
For using **gcc 4.9**, do you mean for both `MXNet` and `byteps`, or just `byteps`? I will use gcc4.9 to recompile everything, and also look into the pinned memory on PowerPC.

**Comment by bobzhuyb** [comment]
@juncgu The problem happens when your mxnet and byteps are built with different gcc versions. If you install mxnet using pip, it's usually built with gcc 4.9. That's why we ask.you to also use gcc 4.9 for byteps.

How about using 2 GPUs? Does it work?

**Comment by cham-3** [comment]
@bobzhuyb Hi, I met a different issue when I run distributed training with mxnet. 
I use 4 gpus for each worker.
<img width="1401" alt="failure" src="https://user-images.githubusercontent.com/6070040/60557954-f9db1900-9d79-11e9-90e0-7b2fe0ebb712.png">
And everything is ok when I use 1 gpu for each worker.

**Comment by bobzhuyb** [comment]
@cham-3 Would you let us know your environment and how you run the program?  Did you follow the step-by-step tutorial, or did you use other commands to start?

**Comment by cham-3** [comment]
@bobzhuyb 
OS: ubuntu 16.04
gcc: 5.4.0
cuda: 90
mxnet: 1.4.1
And I run the program as followed.
`
worker0 10.255.0.56:
export DMLC_ROLE=worker;
export DMLC_PS_ROOT_URI=10.255.0.56;
export DMLC_PS_ROOT_PORT=9000;
export DMLC_WORKER_ID=0;
export DMLC_NUM_WORKER=2;
export DMLC_NUM_SERVER=1;
python /root/scp/project/byteps/launcher/launch.py python train_bps.py

worker1 10.255.0.101:
export DMLC_ROLE=worker;
export DMLC_PS_ROOT_URI=10.255.0.56;
export DMLC_PS_ROOT_PORT=9000;
export DMLC_WORKER_ID=1;
export DMLC_NUM_WORKER=2;
export DMLC_NUM_SERVER=1;
python /root/scp/project/byteps/launcher/launch.py python train_bps.py

server:
export DMLC_ROLE=server;
export DMLC_PS_ROOT_URI=10.255.0.56;
export DMLC_PS_ROOT_PORT=9000;
export DMLC_NUM_WORKER=2;
export DMLC_NUM_SERVER=1;
python /root/scp/project/byteps/launcher/launch.py

scheduler:
export DMLC_ROLE=scheduler;
export DMLC_PS_ROOT_URI=10.255.0.56;
export DMLC_PS_ROOT_PORT=9000;
export DMLC_NUM_WORKER=2;
export DMLC_NUM_SERVER=1;
python /root/scp/project/byteps/launcher/launch.py
`

**Comment by bobzhuyb** [comment]
@cham-3 Your commands look good to me. 

How did you install byteps for workers, by using the source code or pip package? 

How did you install byteps for servers, by building our modified MXNet, or using our pip package?

**Comment by cham-3** [comment]
@bobzhuyb I built both environments by the provided dockerfile.

**Comment by bobzhuyb** [comment]
Okay. I saw you write gcc 5.4. The dockerfiles in fact use gcc 4.9. 

Where did you run scheduler? Is it on 10.255.0.56? Can 10.255.0.101 connect to 10.255.0.56 port 9000?

**Comment by cham-3** [comment]
Sorry for that. The environments were built by my colleague in face.

Yes. I run both the scheduler and server on 10.255.0.56. When I ping 10.255.0.56 on 10.255.0.101, it's ok.

**Comment by bobzhuyb** [comment]
Can you do `export PS_VERBOSE=2`, run again, and paste the full logs? Thanks.

**Comment by cham-3** [comment]
No problems. I'll try it.

**Comment by juncgu** [comment]
> @juncgu The problem happens when your mxnet and byteps are built with different gcc versions. If you install mxnet using pip, it's usually built with gcc 4.9. That's why we ask.you to also use gcc 4.9 for byteps.
> 
> How about using 2 GPUs? Does it work?

"2 GPUs" still doesn't work in the original environment.

**Comment by bobzhuyb** [comment]
@juncgu Your error is quite strange.. The error is not in byteps. Do you have an idea how large share memory and pinned memory can your PowerPC machine have? BytePS uses a lot of them (may be several GB per GPU). Is there a way to raise those limits?

**Comment by cham-3** [comment]
@bobzhuyb Hi, I set the environment variable and got log files as followed.
[scheduler.txt](https://github.com/bytedance/byteps/files/3353481/scheduler.txt)
[server.txt](https://github.com/bytedance/byteps/files/3353482/server.txt)
[worker0.txt](https://github.com/bytedance/byteps/files/3353483/worker0.txt)
[worker1.txt](https://github.com/bytedance/byteps/files/3353484/worker1.txt)

**Comment by bobzhuyb** [comment]
@cham-3 Thanks. So they run for a while before crashes. We'll look into this.

@ymjiang Check the log..

**Comment by ymjiang** [comment]
@cham-3 Can you show the value of this env `BYTEPS_SERVER_MXNET_PATH` on your environment? Besides, is this bug reproducible? That is, if you launch the task again, does it run into the same bug and crashed at the same step? (e.g., if it crashes, the timestamp should be about 9499)

**Comment by cham-3** [comment]
@ymjiang Thank you for your replying. I found that  the env `BYTEPS_SERVER_MXNET_PATH ` is only set on server and scheduler. Should I set it on all nodes?
![env](https://user-images.githubusercontent.com/6070040/60571142-923ac300-9da5-11e9-9fdb-82da5dbeaf2e.png)
Yes, it's reproducible.

**Comment by bobzhuyb** [comment]
@cham-3 No, only server and scheduler needs it. Let me clarify again, you used the dockerfiles (https://github.com/bytedance/byteps/blob/master/docker/Dockerfile.worker.mxnet.cu90 and https://github.com/bytedance/byteps/blob/master/docker/Dockerfile.server) to build your own docker images, and then start worker/server/scheduler using these images. Is this correct?

**Comment by cham-3** [comment]
@bobzhuyb Yes. My colleague built the environment following the tutorial last Friday.

**Comment by bobzhuyb** [comment]
@ymjiang I see the problem. You added ZMQ_DONTWAIT flag (https://github.com/bytedance/ps-lite/blob/byteps/src/zmq_van.h#L339), but did not handle EAGAIN in the following loop (https://github.com/bytedance/ps-lite/blob/byteps/src/zmq_van.h#L346).

I actually don't think you need the ZMQ_DONTWAIT flag for sending.

**Comment by ymjiang** [comment]
@cham-3 Sorry for the bug. 931b54a3f2025013daf7a6196bc78bf6a099bfa8 should fix this. Please try and let us know if it works. 

You may uninstall byteps 
```
pip uninstall -y byteps
python setup.py clean --all
```
and then start over.

**Comment by cham-3** [comment]
@ymjiang Hi, I rebuilt byteps as you described.
I met a different problem when I run the program.
![image](https://user-images.githubusercontent.com/6070040/60580174-31b48180-9db7-11e9-8763-9b3e5af1afd9.png)

**Comment by ymjiang** [comment]
@cham-3 Did you set `NVIDIA_VISIBLE_DEVICES`? I don't see it from the commands you provide:

> @bobzhuyb
> OS: ubuntu 16.04
> gcc: 5.4.0
> cuda: 90
> mxnet: 1.4.1
> And I run the program as followed.
> `
> worker0 10.255.0.56:
> export DMLC_ROLE=worker;
> export DMLC_PS_ROOT_URI=10.255.0.56;
> export DMLC_PS_ROOT_PORT=9000;
> export DMLC_WORKER_ID=0;
> export DMLC_NUM_WORKER=2;
> export DMLC_NUM_SERVER=1;
> python /root/scp/project/byteps/launcher/launch.py python train_bps.py
> 
> worker1 10.255.0.101:
> export DMLC_ROLE=worker;
> export DMLC_PS_ROOT_URI=10.255.0.56;
> export DMLC_PS_ROOT_PORT=9000;
> export DMLC_WORKER_ID=1;
> export DMLC_NUM_WORKER=2;
> export DMLC_NUM_SERVER=1;
> python /root/scp/project/byteps/launcher/launch.py python train_bps.py
> 
> server:
> export DMLC_ROLE=server;
> export DMLC_PS_ROOT_URI=10.255.0.56;
> export DMLC_PS_ROOT_PORT=9000;
> export DMLC_NUM_WORKER=2;
> export DMLC_NUM_SERVER=1;
> python /root/scp/project/byteps/launcher/launch.py
> 
> scheduler:
> export DMLC_ROLE=scheduler;
> export DMLC_PS_ROOT_URI=10.255.0.56;
> export DMLC_PS_ROOT_PORT=9000;
> export DMLC_NUM_WORKER=2;
> export DMLC_NUM_SERVER=1;
> python /root/scp/project/byteps/launcher/launch.py
> `

**Comment by cham-3** [comment]
@ymjiang No. Is it necessary? I set the env CUDA_VISIBLE_DEVICES=0,1,2,3 in my training scripts.

**Comment by ymjiang** [comment]
It is necessary for BytePS [launcher](https://github.com/bytedance/byteps/blob/master/launcher/launch.py#L26). You should set `export NVIDIA_VISIBLE_DEVICES=0,1,2,3` before you run the script using the launcher.

**Comment by bobzhuyb** [comment]
@cham-3 Your new problem is because you did not pin gcc to 4.9. You can pin it and rebuild it, or you can just rebuild the whole docker image using the docker files.

**Comment by juncgu** [comment]
> @juncgu Your error is quite strange.. The error is not in byteps. Do you have an idea how large share memory and pinned memory can your PowerPC machine have? BytePS uses a lot of them (may be several GB per GPU). Is there a way to raise those limits?

The errors remain after recompiling everything using gcc-4.8.5 (my machines do not have gcc-4.9). 
BTW, I want to double confirm whether `byteps` is compatible with `cuda-9.2`.
If yes, then the problem should come from PowerPC.

There is (almost) no limit on shared memory in PowerPC. With `ipcs -al`, I can see
```text
------ Shared Memory Limits --------
max number of segments = 4096
max seg size (kbytes) = 18014398509465599
max total shared memory (kbytes) = 18014397435740096
min seg size (bytes) = 1
```

**Comment by bobzhuyb** [comment]
@juncgu We tested cuda 9.0 and 10.0. Not entirely sure about 9.2, though I don't think it will be a problem.

Does MXNet-Horovod work for you?

**Comment by juncgu** [comment]
> @juncgu We tested cuda 9.0 and 10.0. Not entirely sure about 9.2, though I don't think it will be a problem.
> 
> Does MXNet-Horovod work for you?

Thank you, @bobzhuyb. I will try it out.

**Comment by juncgu** [comment]
> @juncgu We tested cuda 9.0 and 10.0. Not entirely sure about 9.2, though I don't think it will be a problem.
> 
> Does MXNet-Horovod work for you?

Hi, @bobzhuyb.  
[Horovod (v0.16.1)](https://github.com/horovod/horovod/tree/v0.16.1) + MXNet(bytedance version) works in my environment (mentioned at the top of this issue). (I ran an experiment with 2 machines ( 4 GPUs each).)

My error was caused by https://github.com/bytedance/byteps/blob/ac2f11c43b9b004f641e69d4db7e1ec03ef2f955/example/mxnet/common/data_byteps.py#L85 and https://github.com/bytedance/byteps/blob/ac2f11c43b9b004f641e69d4db7e1ec03ef2f955/example/mxnet/common/data_byteps.py#L86, where the NDArray context is "cpu_pinned" and its device is 0. 

From [mxnet.context.cpu_pinned](https://beta.mxnet.io/api/gluon-related/_autogen/mxnet.context.cpu_pinned.html), it says "device_id" is for GPU, and not needed for CPU. I am not sure how it will affect "cpu_pinned" context. **I tried to change the device_id in those two lines to be the gpu id of each process (or "BYTEPS_LOCAL_RANK").** And the job (4GPUs, single worker node) passed the previous error and went to the training stage. However, another error occurs:
```text
[2019-07-08 11:04:25.182406: F byteps/common/core_loops.cc:563] Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading CUDA: unknown error
[2019-07-08 11:04:26.[247341: 2019-07-08 11:04:26F.247369 byteps/common/core_loops.cc: :563] F Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading CUDA: unknown errorbyteps/common/core_loops.cc
:563] Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading CUDA: unknown error
[2019-07-08 11:04:26.247368: F byteps/common/core_loops.cc:563] Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading CUDA: unknown error
```
This error is caused by https://github.com/bytedance/byteps/blob/ac2f11c43b9b004f641e69d4db7e1ec03ef2f955/byteps/common/core_loops.cc#L563. 

Do you have any experience or thoughts on this problem?

Thank you

**Comment by bobzhuyb** [comment]
@juncgu For tensors on CPU, the context ID should be -1. Can you try passing in -1, or not passing it at all?

**Comment by juncgu** [comment]
> @juncgu For tensors on CPU, the context ID should be -1. Can you try passing in -1, or not passing it at all?

Thank you for your continuous help, @bobzhuyb.
It works with "**passing in -1**". ("not passing" doesn't work.)

**Comment by bobzhuyb** [comment]
Thanks. I am not entirely sure why this problem did not appear in our testing. I actually think it's MXNet's problem, especially not passing it does not work. We will fix `mx.Context('cpu_pinned', 0))` in our example anyways.

**Comment by yangwenhuan** [comment]
@juncgu , I wonder how to determine DMLC_PS_ROOT_PORT in RoCE? thanks.

**Comment by juncgu** [comment]
> @juncgu , I wonder how to determine DMLC_PS_ROOT_PORT in RoCE? thanks.

Hi @yangwenhuan,

In my experience, I just randomly pick a free port (from 1024) and assign to`DMLC_PS_ROOT_PORT`, which is similar to pick a port for regular TCP server-client example. 
I think the `DMLC_PS_ROOT_PORT` is needed for building a socket connection which is used to exchange RDMA connection information for the following RDMA connection. Therefore, there should be no specific regulations in terms of port selection. Please correct me if I am incorrect.

Thank you.
