### ISSUE TITLE
broadcast_optimizer_state in pytorch needs to be able to handle NoneType params

### ISSUE THREAD

**Issue by dbonner** [bytedance/byteps#362]
export NVIDIA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 # 8 GPU machine
export DMLC_WORKER_ID=0 # your worker id
export DMLC_NUM_WORKER=1 # one worker
export DMLC_ROLE=worker
export DMLC_NUM_SERVER=1
export DMLC_PS_ROOT_URI=localhost
export DMLC_PS_ROOT_PORT=10000
bpslaunch python byteps/example/pytorch/benchmark_byteps.py --fp16-pushpull

Traceback (most recent call last):                                                                     
  File "...benchmark_byteps.py", line 72, in <module>
    bps.broadcast_optimizer_state(optimizer, root_rank=0)              
File "/home/daniel/py38/lib/python3.8/site-packages/byteps/torch/__init__.py", line 398, in broadcast
_optimizer_state                                                                                       
    p = torch.Tensor([p]).cuda()                                                                       
TypeError: must be real number, not NoneType

This is because the latest pytorch from source includes NoneType parameters in optimizer_state.

I have proposed a fix.

**Comment by dbonner** [comment]
Hi,
Now that PyTorch 1.8 is about to be released:
You will find that this problem is not resolved:

export NVIDIA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 # 8 GPU machine
export DMLC_WORKER_ID=0 # your worker id
export DMLC_NUM_WORKER=1 # one worker
export DMLC_ROLE=worker
export DMLC_NUM_SERVER=1
export DMLC_PS_ROOT_URI=localhost
export DMLC_PS_ROOT_PORT=10000
bpslaunch python byteps/example/pytorch/benchmark_byteps.py --fp16-pushpull

BytePS launching worker
Traceback (most recent call last):
  File "/home/daniel/localgpu/byteps/example/pytorch/benchmark_byteps.py", line 72, in <module>
Traceback (most recent call last):
  File "/home/daniel/localgpu/byteps/example/pytorch/benchmark_byteps.py", line 72, in <module>
    bps.broadcast_optimizer_state(optimizer, root_rank=0)
  File "/home/daniel/py38/lib/python3.8/site-packages/byteps/torch/__init__.py", line 398, in broadcast_optimizer_state
    bps.broadcast_optimizer_state(optimizer, root_rank=0)
  File "/home/daniel/py38/lib/python3.8/site-packages/byteps/torch/__init__.py", line 398, in broadcast_optimizer_state
    p = torch.Tensor([p]).cuda()
TypeError: must be real number, not NoneType
    p = torch.Tensor([p]).cuda()
TypeError: must be real number, not NoneType
Traceback (most recent call last):
  File "/home/daniel/localgpu/byteps/example/pytorch/benchmark_byteps.py", line 72, in <module>
Traceback (most recent call last):
  File "/home/daniel/localgpu/byteps/example/pytorch/benchmark_byteps.py", line 72, in <module>
    bps.broadcast_optimizer_state(optimizer, root_rank=0)
  File "/home/daniel/py38/lib/python3.8/site-packages/byteps/torch/__init__.py", line 398, in broadcast_optimizer_state
    p = torch.Tensor([p]).cuda()
TypeError: must be real number, not NoneType
    bps.broadcast_optimizer_state(optimizer, root_rank=0)
  File "/home/daniel/py38/lib/python3.8/site-packages/byteps/torch/__init__.py", line 398, in broadcast_optimizer_state
    p = torch.Tensor([p]).cuda()
TypeError: must be real number, not NoneType
Traceback (most recent call last):
  File "/home/daniel/localgpu/byteps/example/pytorch/benchmark_byteps.py", line 72, in <module>
Traceback (most recent call last):
  File "/home/daniel/localgpu/byteps/example/pytorch/benchmark_byteps.py", line 72, in <module>
    bps.broadcast_optimizer_state(optimizer, root_rank=0)
  File "/home/daniel/py38/lib/python3.8/site-packages/byteps/torch/__init__.py", line 398, in broadcast_optimizer_state
Traceback (most recent call last):
  File "/home/daniel/localgpu/byteps/example/pytorch/benchmark_byteps.py", line 72, in <module>
    bps.broadcast_optimizer_state(optimizer, root_rank=0)
  File "/home/daniel/py38/lib/python3.8/site-packages/byteps/torch/__init__.py", line 398, in broadcast_optimizer_state
    p = torch.Tensor([p]).cuda()
TypeError: must be real number, not NoneType
    p = torch.Tensor([p]).cuda()
TypeError: must be real number, not NoneType
    bps.broadcast_optimizer_state(optimizer, root_rank=0)
  File "/home/daniel/py38/lib/python3.8/site-packages/byteps/torch/__init__.py", line 398, in broadcast_optimizer_state
    p = torch.Tensor([p]).cuda()
TypeError: must be real number, not NoneType
Traceback (most recent call last):
  File "/home/daniel/localgpu/byteps/example/pytorch/benchmark_byteps.py", line 72, in <module>
    bps.broadcast_optimizer_state(optimizer, root_rank=0)
  File "/home/daniel/py38/lib/python3.8/site-packages/byteps/torch/__init__.py", line 398, in broadcast_optimizer_state
    p = torch.Tensor([p]).cuda()
TypeError: must be real number, not NoneType
Traceback (most recent call last):
  File "/home/daniel/py38/bin/bpslaunch", line 220, in <module>
    launch_bps()
  File "/home/daniel/py38/bin/bpslaunch", line 206, in launch_bps
    t[i].join()
  File "/home/daniel/py38/bin/bpslaunch", line 34, in join
    raise self.exc
  File "/home/daniel/py38/bin/bpslaunch", line 27, in run
    self.ret = self._target(*self._args, **self._kwargs)
  File "/home/daniel/py38/bin/bpslaunch", line 176, in worker
    subprocess.check_call(command, env=my_env,
  File "/home/daniel/.pyenv/versions/3.8.7/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'python /home/daniel/localgpu/byteps/example/pytorch/benchmark_byteps.py --fp16-pushpull' returned non-zero exit status 1.
