### ISSUE TITLE
subprocess.CalledProcessError   returned non-zero exit status 132

### ISSUE THREAD

**Issue by powermano** [bytedance/byteps#403]
**Describe the bug**
When start first work, it run properly and wait:

```
BytePS launching worker
INFO:root:Namespace(batch_size=64, dtype='float32', epochs=5, j=2, lr=0.01, momentum=0.9, no_cuda=False)
[05:59:38] src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (set the environment variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
   Total params: 440812
   Trainable params: 440812
   Non-trainable params: 0
Shared params in forward computation graph: 0
Unique parameters in model: 440812
--------------------------------------------------------------------------------
[05:59:38] src/postoffice.cc:25: Creating Van: zmq
[05:59:38] src/./zmq_van.h:299: Start ZMQ recv thread
```
Then start second worker, the problem occurs.

**To Reproduce**
1. python 3.5.2
2. cuda_10.2  
3. mxnet=1.8 

**Expected behavior**

**Screenshots**
```
BytePS launching worker
python3 /home/arc-ct6152/github_code/byteps/example/mxnet/train_gluon_mnist_byteps.py
INFO:root:Namespace(batch_size=64, dtype='float32', epochs=5, j=2, lr=0.01, momentum=0.9, no_cuda=False)
[05:51:55] src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (set the environment variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
--------------------------------------------------------------------------------
        Layer (type)                                Output Shape         Param #
================================================================================
               Input                              (1, 1, 28, 28)               0
        Activation-1   <Symbol hybridsequential0_conv0_relu_fwd>               0
        Activation-2                             (1, 20, 24, 24)               0
            Conv2D-3                             (1, 20, 24, 24)             520
         MaxPool2D-4                             (1, 20, 12, 12)               0
        Activation-5   <Symbol hybridsequential0_conv1_relu_fwd>               0
        Activation-6                               (1, 50, 8, 8)               0
            Conv2D-7                               (1, 50, 8, 8)           25050
         MaxPool2D-8                               (1, 50, 4, 4)               0
           Flatten-9                                    (1, 800)               0
       Activation-10  <Symbol hybridsequential0_dense0_relu_fwd>               0
       Activation-11                                    (1, 512)               0
            Dense-12                                    (1, 512)          410112
            Dense-13                                     (1, 10)            5130
================================================================================
Parameters in forward computation graph, duplicate included
   Total params: 440812
   Trainable params: 440812
   Non-trainable params: 0
Shared params in forward computation graph: 0
Unique parameters in model: 440812
--------------------------------------------------------------------------------
Illegal instruction (core dumped)
Traceback (most recent call last):
  File "/usr/local/bin/bpslaunch", line 4, in <module>
    __import__('pkg_resources').run_script('byteps==0.2.5', 'bpslaunch')
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 650, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.5/dist-packages/byteps-0.2.5-py3.5-linux-x86_64.egg/EGG-INFO/scripts/bpslaunch", line 221, in <module>
    launch_bps()
  File "/usr/local/lib/python3.5/dist-packages/byteps-0.2.5-py3.5-linux-x86_64.egg/EGG-INFO/scripts/bpslaunch", line 207, in launch_bps
    t[i].join()
  File "/usr/local/lib/python3.5/dist-packages/byteps-0.2.5-py3.5-linux-x86_64.egg/EGG-INFO/scripts/bpslaunch", line 34, in join
    raise self.exc
  File "/usr/local/lib/python3.5/dist-packages/byteps-0.2.5-py3.5-linux-x86_64.egg/EGG-INFO/scripts/bpslaunch", line 27, in run
    self.ret = self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/dist-packages/byteps-0.2.5-py3.5-linux-x86_64.egg/EGG-INFO/scripts/bpslaunch", line 178, in worker
    stdout=sys.stdout, stderr=sys.stderr, shell=True)
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'python3 /home/arc-ct6152/github_code/byteps/example/mxnet/train_gluon_mnist_byteps.py' returned non-zero exit status 132
```
**Environment (please complete the following information):**
 - OS: ubuntu 
 - GCC version:
 - CUDA and NCCL version:  cuda-10.2   nccl-repo-ubuntu1604-2.6.4-ga-cuda10.0_1-1_amd64
 - Framework (TF, PyTorch, MXNet): MXNet

**Additional context**

**Comment by eric-haibin-lin** [comment]
Could you try to update https://github.com/bytedance/byteps/blob/master/setup.py#L177 with `-march=x86-64` instead?

**Comment by powermano** [comment]
> Could you try to update https://github.com/bytedance/byteps/blob/master/setup.py#L177 with `-march=x86-64` instead?

I used pip install and it works. Thanks.
