### ISSUE TITLE
How did you get the horovod & bytePS performance

### ISSUE THREAD

**Issue by compete369** [bytedance/byteps#68]
I have the same hardware envs, same network, but I could not get the result as you, almost half as you. Any best practices and experience? thanks very much!  for bytePS with 1 instance and 8 GPU, I have similar testing result.

**Comment by ymjiang** [comment]
@compete369 For BytePS, can you please try `export MXNET_OMP_MAX_THREADS=10` for the servers?

**Comment by compete369** [comment]
Hello, I followed your advice except "export MXNET_CPU_WORKER_NTHREADS=32", and got total 4605 imgs/sec with 8 GPUs + 64Core+256GB mem * 2 workers, 16core + 16GB mem *4 servers. Thanks very much!

if including  "export MXNET_CPU_WORKER_NTHREADS=32", the servers are going crazy, then I dropped it.

**2 quick questions:**
1. when the test goes to the end, there is an exception
   Traceback (most recent call last):
  File "/usr/local/byteps/example/pytorch/benchmark_byteps.py", line 132, in <module>
    raise Exception
Traceback (most recent call last):
  File "/usr/local/byteps/example/pytorch/benchmark_byteps.py", line 132, in <module>
Exception
    raise Exception
Exception
Traceback (most recent call last):
  File "/usr/local/byteps/example/pytorch/benchmark_byteps.py", line 132, in <module>
    raise Exception
Traceback (most recent call last):
  File "/usr/local/byteps/example/pytorch/benchmark_byteps.py", line 132, in <module>
Exception    raise Exception

Exception
Traceback (most recent call last):
  File "/usr/local/byteps/example/pytorch/benchmark_byteps.py", line 132, in <module>
    raise Exception
Exception
Traceback (most recent call last):
  File "/usr/local/byteps/example/pytorch/benchmark_byteps.py", line 132, in <module>
    raise Exception
Exception
Traceback (most recent call last):
  File "/usr/local/byteps/example/pytorch/benchmark_byteps.py", line 132, in <module>
    raise Exception
Exception
Traceback (most recent call last):
Iter #99: 289.7 img/sec per GPU
  File "/usr/local/byteps/example/pytorch/benchmark_byteps.py", line 132, in <module>
    raise Exception

2. do you know how to analysis the NCCL Ring? I am wondering whether the ring takes use of NVlink correctly?
  worker-pytorch-0:45:45 [7] NCCL INFO Ring 00 : 3[7] -> 0[4] via P2P/IPC
worker-pytorch-0:42:42 [5] NCCL INFO Ring 00 : 1[5] -> 2[6] via P2P/IPC
worker-pytorch-0:46:46 [6] NCCL INFO Ring 00 : 2[6] -> 3[7] via P2P/IPC
worker-pytorch-0:41:41 [4] NCCL INFO Ring 00 : 0[4] -> 1[5] via P2P/IPC
worker-pytorch-0:41:41 [4] NCCL INFO Ring 01 : 0[4] -> 2[6] via P2P/IPC
worker-pytorch-0:42:42 [5] NCCL INFO Ring 01 : 1[5] -> 3[7] via P2P/IPC
worker-pytorch-0:45:45 [7] NCCL INFO Ring 01 : 3[7] -> 0[4] via P2P/IPC
worker-pytorch-0:46:46 [6] NCCL INFO Ring 01 : 2[6] -> 1[5] via P2P/IPC
worker-pytorch-0:41:41 [4] NCCL INFO Ring 02 : 0[4] -> 3[7] via P2P/IPC
worker-pytorch-0:46:46 [6] NCCL INFO Ring 02 : 2[6] -> 0[4] via P2P/IPC
worker-pytorch-0:45:45 [7] NCCL INFO Ring 02 : 3[7] -> 1[5] via P2P/IPC
worker-pytorch-0:42:42 [5] NCCL INFO Ring 02 : 1[5] -> 2[6] via P2P/IPC
worker-pytorch-0:46:46 [6] NCCL INFO Ring 03 : 2[6] -> 1[5] via P2P/IPC
worker-pytorch-0:42:42 [5] NCCL INFO Ring 03 : 1[5] -> 0[4] via P2P/IPC
worker-pytorch-0:41:41 [4] NCCL INFO Ring 03 : 0[4] -> 3[7] via P2P/IPC
worker-pytorch-0:45:45 [7] NCCL INFO Ring 03 : 3[7] -> 2[6] via P2P/IPC
worker-pytorch-0:45:45 [7] NCCL INFO Ring 04 : 3[7] -> 0[4] via P2P/IPC
worker-pytorch-0:42:42 [5] NCCL INFO Ring 04 : 1[5] -> 2[6] via P2P/IPC
worker-pytorch-0:41:41 [4] NCCL INFO Ring 04 : 0[4] -> 1[5] via P2P/IPC
worker-pytorch-0:46:46 [6] NCCL INFO Ring 04 : 2[6] -> 3[7] via P2P/IPC
worker-pytorch-0:46:46 [6] NCCL INFO Ring 05 : 2[6] -> 1[5] via P2P/IPC
worker-pytorch-0:41:41 [4] NCCL INFO Ring 05 : 0[4] -> 2[6] via P2P/IPC
worker-pytorch-0:45:45 [7] NCCL INFO Ring 05 : 3[7] -> 0[4] via P2P/IPC
worker-pytorch-0:42:42 [5] NCCL INFO Ring 05 : 1[5] -> 3[7] via P2P/IPC
worker-pytorch-0:42:42 [5] NCCL INFO Ring 06 : 1[5] -> 2[6] via P2P/IPC
worker-pytorch-0:41:41 [4] NCCL INFO Ring 06 : 0[4] -> 3[7] via P2P/IPC
worker-pytorch-0:45:45 [7] NCCL INFO Ring 06 : 3[7] -> 1[5] via P2P/IPC
worker-pytorch-0:46:46 [6] NCCL INFO Ring 06 : 2[6] -> 0[4] via P2P/IPC
worker-pytorch-0:46:46 [6] NCCL INFO Ring 07 : 2[6] -> 1[5] via P2P/IPC
worker-pytorch-0:45:45 [7] NCCL INFO Ring 07 : 3[7] -> 2[6] via P2P/IPC
worker-pytorch-0:42:42 [5] NCCL INFO Ring 07 : 1[5] -> 0[4] via P2P/IPC
worker-pytorch-0:41:41 [4] NCCL INFO Ring 07 : 0[4] -> 3[7] via P2P/IPC

**Comment by ymjiang** [comment]
@compete369 Good to know you get performance improvement. 

1. We fixed the exception raising in https://github.com/bytedance/byteps/commit/b825042a29d75fe58e30636c738113fabffe41bd. The code in our docker images are stale though. We will update the images. For now you can manually update the code and remake.

2. Perhaps take a look at `nvidia-smi nvlink -sc`. [This](https://blog.exxactcorp.com/exploring-nvidia-nvlink-nvidia-smi-commands/) might be helpful.
---
> if including "export MXNET_CPU_WORKER_NTHREADS=32", the servers are going crazy, then I dropped it.

Besides, what does "crazy" mean? Does it mean bad performance?

**Comment by compete369** [comment]
crazy: CPU goes very high, about 100%, but the GPU utilization goes down to 2-10%. Thanks very much for your instruction.

**Comment by ymjiang** [comment]
@compete369 That sounds like your cpu becomes the bottleneck. Perhaps you can reduce `MXNET_CPU_WORKER_NTHREADS` to 16 or even smaller value. It requires some tuning.

**Comment by saadalqasim** [comment]
Do you believe we still looking for cash here .. please Who can donating to me and my 2 children? And Is the computer working impossible? I wish I travel to space 🤲🏻

**Comment by spgeaney113** [comment]
Doesn't really help me much

**Comment by Bama4542** [comment]
Hasn't really done much good for me either it's got quite a few bugs to
work out!!! Did you like the way it's setup?

**Comment by bobzhuyb** [comment]
@spgeaney113 @Bama4542 If you have specific questions, please open new issues. You are only spamming this thread now.

**Comment by compete369** [comment]
How did you test the performance report on the main page?  synthetic or real imagenet on the NAS. I tested the horovod,  with 32 GPUs, the performance dropped 20%(8300 -> 6477)

**Comment by ymjiang** [comment]
@compete369 We used synthetic data in the performance report.

**Comment by compete369** [comment]
Could share which public cloud you relied on if possible? Just curious about the good network stableness and performance. Thanks!
