### ISSUE TITLE
Stuck with keras example provided by byteps

### ISSUE THREAD

**Issue by CDCrystal** [bytedance/byteps#71]
My command is just like:
python /usr/local/byteps/launcher/launch.py       /usr/local/byteps/example/keras/run_keras.sh  --batch-size=32 --num-iters=2
The two workers stuck:
![image](https://user-images.githubusercontent.com/43447571/61859673-29092400-aefb-11e9-8d19-d2424b63fff3.png)
![image](https://user-images.githubusercontent.com/43447571/61859693-31f9f580-aefb-11e9-9f83-ebc276fa6feb.png)
While the server and scheduler:
~# python /usr/local/byteps/launcher/launch.py
BytePS launching server
[08:26:36] [08:26:36] src/customer.ccsrc/kvstore/././kvstore_dist_server.h:166: Enable zero copy of pull operations.
:226: Use seperate thread to process pull requests from each worker.
[08:26:36] src/customer.cc:239: Server uses 1 threads to process push requests.
[08:26:36] src/customer.cc:93: Server inits Pull Thread-1
[08:26:36] src/customer.cc:93: Server inits Pull Thread-0
[08:26:36] src/customer.cc:137: Server inits Push Thread-0
[08:26:36] src/customer.cc:258: All threads inited, ready to process message
[08:26:36] src/./zmq_van.h:285: Start ZMQ recv thread

python /usr/local/byteps/launcher/launch.py
BytePS launching scheduler
[08:26:22] src/./zmq_van.h:285: Start ZMQ recv thread

Following the instruction from https://github.com/bytedance/byteps/blob/master/docs/step-by-step-tutorial.md
I've changed the environment variable to: export EVAL_TYPE=mnist_advanced
and I tried the tensorflow workers with mnist example(/usr/local/byteps/example/tensorflow/tensorflow_mnist.py) and it done well.
I'm confused. Could you help me out?

**Comment by ymjiang** [comment]
Can you please show the output with `PS_VERBOSE=1` (on all scheduler/server/worker)?  We need to confirm whether the connections have been established. Thank you.

**Comment by CDCrystal** [comment]
Hi, @ymjiang , I kill the processes with "kill -9 xxx", and restart all the scheduler/server/workers, it just strangely work! 
After pull the docker images provided by the docs.
I've written the configuration to .bashrc just as following:
Scheduler:
export DMLC_NUM_WORKER=2
export DMLC_ROLE=scheduler
export DMLC_NUM_SERVER=1
export DMLC_PS_ROOT_URI=10.18.97.15 # the scheduler IP
export DMLC_PS_ROOT_PORT=1234  # the scheduler port
export PS_VERBOSE=1

The executed command is: python /usr/local/byteps/launcher/launch.py
-------------------------------
Server:
export DMLC_NUM_WORKER=2
export DMLC_ROLE=server
export DMLC_NUM_SERVER=1
export DMLC_PS_ROOT_URI=10.18.97.15 # the scheduler IP
export DMLC_PS_ROOT_PORT=1234  # the scheduler port
export PS_VERBOSE=1

The executed command is: python /usr/local/byteps/launcher/launch.py
-------------------------------
Worker 0:
export NVIDIA_VISIBLE_DEVICES=0  # only 1 GPU
export DMLC_WORKER_ID=0 # your worker id
export DMLC_NUM_WORKER=2 # you only have one worker
export DMLC_ROLE=worker # your role is worker
export DMLC_NUM_SERVER=1
export DMLC_PS_ROOT_URI=10.18.97.15 # the scheduler IP
export DMLC_PS_ROOT_PORT=1234 # the scheduler port

export EVAL_TYPE=mnist_advanced
export PS_VERBOSE=1

The executed command is:
python /usr/local/byteps/launcher/launch.py /usr/local/byteps/example/keras/run_keras.sh --batch-size=32 --num-iters=2
-------------------------------
Worker 1:
export NVIDIA_VISIBLE_DEVICES=0  # only 1 GPU
export DMLC_WORKER_ID=1 # worker-1
export DMLC_NUM_WORKER=2 # 2 workers
export DMLC_ROLE=worker # your role is worker
export DMLC_NUM_SERVER=1
export DMLC_PS_ROOT_URI=10.18.97.15 # the scheduler IP
export DMLC_PS_ROOT_PORT=1234 # the scheduler port

export EVAL_TYPE=mnist_advanced
export PS_VERBOSE=1

The executed command is:
python /usr/local/byteps/launcher/launch.py /usr/local/byteps/example/keras/run_keras.sh --batch-size=32 --num-iters=2

While I run with the configuration, the output is:
Scheduler:
BytePS launching scheduler
[03:56:19] src/./zmq_van.h:61: BYTEPS_ZMQ_MAX_SOCKET set to 1024
[03:56:19] src/./zmq_van.h:66: BYTEPS_ZMQ_NTHREADS set to 4
[[03:56:19] src/van.cc:357: Bind to role=scheduler, id=1, ip=10.18.97.15, port=1234, is_recovery=0
03:56:19] src/./zmq_van.h:285: Start ZMQ recv thread
[03:56:53] src/van.cc:108: assign rank=9 to node role=worker, ip=10.18.96.4, port=58557, is_recovery=0
[03:56:53] src/van.cc:108: assign rank=11 to node role=worker, ip=10.18.96.13, port=37605, is_recovery=0
[03:56:53] src/van.cc:108: assign rank=8 to node role=server, ip=10.18.101.97, port=39399, is_recovery=0
[03:56:53] src/van.cc:134: the scheduler is connected to 2 workers and 1 servers
[03:56:53] src/van.cc:233: Barrier count for 7 : 1
[03:56:53] src/van.cc:233: Barrier count for 7 : 2
[03:56:53] src/van.cc:233: Barrier count for 7 : 3
[03:56:53] src/van.cc:233: Barrier count for 7 : 4
[03:56:53] src/van.cc:233: Barrier count for 7 : 1
------------------------------------
Server:
BytePS launching server
[03:56:20] src/kvstore/././kvstore_dist_server.h:166: Enable zero copy of pull operations.
[03:56:20] src/customer.cc:226: Use seperate thread to process pull requests from each worker.
[03:56:20] src/./zmq_van.h:61: BYTEPS_ZMQ_MAX_SOCKET set to 1024
[03:56:20] src/./zmq_van.h:66: BYTEPS_ZMQ_NTHREADS set to 4
[03:56:20] src/customer.cc:239: Server uses 1 threads to process push requests.
[03:56:20] src/van.cc:357: Bind to role=server, ip=10.18.101.97, port=39399, is_recovery=0
[03:56:20] src/customer.cc:93: Server inits Pull Thread-1
[03:56:20] src/customer.cc:93: Server inits Pull Thread-0
[03:56:20] src/customer.cc:137: Server inits Push Thread-0
[03:56:20] src/customer.cc:258: All threads inited, ready to process message
[03:56:20] src/./zmq_van.h:285: Start ZMQ recv thread
[03:56:53] src/van.cc:306: S[8] is connected to others
------------------------------------
Worker 0:
BytePS launching worker
Run Keras MNIST-advanced ...
[03:56:53] src/customer.cc:363: Do not use thread pool for receiving.
[03:56:53] src/./zmq_van.h:285: Start ZMQ recv thread
[03:56:53] src/./zmq_van.h:285: Start ZMQ recv thread
[03:56:53] src/./zmq_van.h:285: Start ZMQ recv thread
2019-07-26 03:56:54.692924: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2019-07-26 03:56:54.711678: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties:
name: Tesla V100-PCIE-32GB major: 7 minor: 0 memoryClockRate(GHz): 1.38
pciBusID: 0000:18:00.0
totalMemory: 31.72GiB freeMemory: 31.31GiB
2019-07-26 03:56:54.711705: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2019-07-26 03:56:54.711722: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-07-26 03:56:54.711731: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0
2019-07-26 03:56:54.711739: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N
2019-07-26 03:56:54.712606: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 30460 MB memory) -> physical GPU (device: 0, name: Tesla V100-PCIE-32GB, pci bus id: 0000:18:00.0, compute capability: 7.0)
Downloading data from https://storage.googleapis.com/tensorflow/tf-keras-datasets/mnist.npz
11501568/11490434 [==============================] - 1s 0us/step
x_train shape: (60000, 28, 28, 1)
60000 train samples
10000 test samples

Then it starts training.
------------------------------------
Worker 1:
BytePS launching worker
Run Keras MNIST-advanced ...
[03:56:50] src/./zmq_van.h:61: [BYTEPS_ZMQ_MAX_SOCKET set to 1024
03:56:50] src/customer.cc:[03:56:50363: Do not use thread pool for receiving.
] src/./zmq_van.h:66: BYTEPS_ZMQ_NTHREADS set to 4
[03:56:50[] src/van.cc:357: Bind to role=worker, ip=10.18.96.13, port=37605, is_recovery=0
03:56:50] src/./zmq_van.h:285: Start ZMQ recv thread
[03:56:53] src/./zmq_van.h:285: Start ZMQ recv thread
[03:56:53] src/./zmq_van.h:285: Start ZMQ recv thread
[03:56:53] src/van.cc:306: W[11] is connected to others
2019-07-26 03:56:54.633928: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2019-07-26 03:56:54.657151: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties:
name: Tesla P100-PCIE-16GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285
pciBusID: 0000:18:00.0
totalMemory: 15.90GiB freeMemory: 15.54GiB
2019-07-26 03:56:54.657222: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2019-07-26 03:56:54.657260: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-07-26 03:56:54.657279: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0
2019-07-26 03:56:54.657298: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N
2019-07-26 03:56:54.657884: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 15120 MB memory) -> physical GPU (device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:18:00.0, compute capability: 6.0)
Downloading data from https://storage.googleapis.com/tensorflow/tf-keras-datasets/mnist.npz
11501568/11490434 [==============================] - 1s 0us/step
x_train shape: (60000, 28, 28, 1)
60000 train samples
10000 test samples

Then it starts training.
>>>>>>>>>>>>>>>>>>>
After that, I get the following errors:
Worker 0:
Test loss: 0.02005128543750852
Test accuracy: 0.9938
[04:22:10] 3rdparty/ps-lite/include/dmlc/logging.h:276: [04:22:10] src/./zmq_van.h:304: Check failed: 0 failed to receive message. errno: 88 Socket operation on non-socket

Stack trace returned 6 entries:
[bt] (0) /usr/local/lib/python2.7/dist-packages/byteps-0.1.0-py2.7-linux-x86_64.egg/byteps/tensorflow/c_lib.so(+0x31ef8) [0x7f9483c50ef8]
[bt] (1) /usr/local/lib/python2.7/dist-packages/byteps-0.1.0-py2.7-linux-x86_64.egg/byteps/tensorflow/c_lib.so(+0x32e19) [0x7f9483c51e19]
[bt] (2) /usr/local/lib/python2.7/dist-packages/byteps-0.1.0-py2.7-linux-x86_64.egg/byteps/tensorflow/c_lib.so(+0x83c08) [0x7f9483ca2c08]
[bt] (3) /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb8c80) [0x7f950cacac80]
[bt] (4) /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba) [0x7f95ac2436ba]
[bt] (5) /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f95abf7941d]


terminate called after throwing an instance of 'dmlc::Error'
  what():  [04:22:10] src/./zmq_van.h:304: Check failed: 0 failed to receive message. errno: 88 Socket operation on non-socket

Stack trace returned 6 entries:
[bt] (0) /usr/local/lib/python2.7/dist-packages/byteps-0.1.0-py2.7-linux-x86_64.egg/byteps/tensorflow/c_lib.so(+0x31ef8) [0x7f9483c50ef8]
[bt] (1) /usr/local/lib/python2.7/dist-packages/byteps-0.1.0-py2.7-linux-x86_64.egg/byteps/tensorflow/c_lib.so(+0x32e19) [0x7f9483c51e19]
[bt] (2) /usr/local/lib/python2.7/dist-packages/byteps-0.1.0-py2.7-linux-x86_64.egg/byteps/tensorflow/c_lib.so(+0x83c08) [0x7f9483ca2c08]
[bt] (3) /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb8c80) [0x7f950cacac80]
[bt] (4) /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba) [0x7f95ac2436ba]
[bt] (5) /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f95abf7941d]


/usr/local/byteps/example/keras/run_keras.sh: line 17:  1772 Aborted                 (core dumped) python $path/keras_mnist_advanced.py $@
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/byteps/launcher/launch.py", line 18, in worker
    subprocess.check_call(command, env=my_env, stdout=sys.stdout, stderr=sys.stderr, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '/usr/local/byteps/example/keras/run_keras.sh --batch-size=32 --num-iters=2' returned non-zero exit status 134
------------------------------------
Worker 1:
Test loss: 0.020051285918699615
Test accuracy: 0.9938
[04:22:10] src/./zmq_van.h:72: W[11] is stopping
[04:22:10] src/van.cc:87: W[11] is stopped
[04:22:10] 3rdparty/ps-lite/include/dmlc/logging.h:276: [04:22:10] src/./zmq_van.h:304: Check failed: 0 failed to receive message. errno: 88 Socket operation on non-socket

Stack trace returned 6 entries:
[bt] (0) /usr/local/lib/python2.7/dist-packages/byteps-0.1.0-py2.7-linux-x86_64.egg/byteps/tensorflow/c_lib.so(+0x31ef8) [0x7f3409f60ef8]
[bt] (1) /usr/local/lib/python2.7/dist-packages/byteps-0.1.0-py2.7-linux-x86_64.egg/byteps/tensorflow/c_lib.so(+0x32e19) [0x7f3409f61e19]
[bt] (2) /usr/local/lib/python2.7/dist-packages/byteps-0.1.0-py2.7-linux-x86_64.egg/byteps/tensorflow/c_lib.so(+0x83c08) [0x7f3409fb2c08]
[bt] (3) /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb8c80) [0x7f3492c4bc80]
[bt] (4) /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba) [0x7f35323c46ba]
[bt] (5) /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f35320fa41d]


terminate called after throwing an instance of 'dmlc::Error'
  what():  [04:22:10] src/./zmq_van.h:304: Check failed: 0 failed to receive message. errno: 88 Socket operation on non-socket

Stack trace returned 6 entries:
[bt] (0) /usr/local/lib/python2.7/dist-packages/byteps-0.1.0-py2.7-linux-x86_64.egg/byteps/tensorflow/c_lib.so(+0x31ef8) [0x7f3409f60ef8]
[bt] (1) /usr/local/lib/python2.7/dist-packages/byteps-0.1.0-py2.7-linux-x86_64.egg/byteps/tensorflow/c_lib.so(+0x32e19) [0x7f3409f61e19]
[bt] (2) /usr/local/lib/python2.7/dist-packages/byteps-0.1.0-py2.7-linux-x86_64.egg/byteps/tensorflow/c_lib.so(+0x83c08) [0x7f3409fb2c08]
[bt] (3) /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb8c80) [0x7f3492c4bc80]
[bt] (4) /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba) [0x7f35323c46ba]
[bt] (5) /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f35320fa41d]


/usr/local/byteps/example/keras/run_keras.sh: line 17:   608 Aborted                 (core dumped) python $path/keras_mnist_advanced.py $@
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/byteps/launcher/launch.py", line 18, in worker
    subprocess.check_call(command, env=my_env, stdout=sys.stdout, stderr=sys.stderr, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '/usr/local/byteps/example/keras/run_keras.sh --batch-size=32 --num-iters=2' returned non-zero exit status 134
------------------------------------
I kill all the processes with "kill -9 xxx" on every docker, or it would not be used for another training command:
python /usr/local/byteps/launcher/launch.py /usr/local/byteps/example/keras/run_keras.sh --batch-size=128

Meanwhile, it seems that I cannot interrupt the training process with Ctrl-C, I have to stop the docker container. (I am not sure if there are other ways.)

>>>>>>>>>>>>>>>>>>>>>
It seems that every epoch takes about 60s with 2 workers and 128 batch size, is this normal? 
Epoch 1/24
234/234 [==============================] - 65s 277ms/step - loss: 0.6020 - acc: 0.8053 - val_loss: 0.0657 - val_acc: 0.9784
Epoch 2/24
234/234 [==============================] - 61s 262ms/step - loss: 0.2013 - acc: 0.9380 - val_loss: 0.0376 - val_acc: 0.9877
Epoch 3/24
234/234 [==============================] - 64s 275ms/step - loss: 0.1484 - acc: 0.9553 - val_loss: 0.0289 - val_acc: 0.9903
Epoch 4/24
234/234 [==============================] - 62s 263ms/step - loss: 0.1223 - acc: 0.9624 - val_loss: 0.0289 - val_acc: 0.9905
Epoch 5/24
233/234 [============================>.] - ETA: 0s - loss: 0.1121 - acc: 0.9653
234/234 [==============================] - 59s 250ms/step - loss: 0.1128 - acc: 0.9652 - val_loss: 0.0341 - val_acc: 0.9892
Epoch 6/24
234/234 [==============================] - 63s 267ms/step - loss: 0.0978 - acc: 0.9694 - val_loss: 0.0253 - val_acc: 0.9917

Many thanks for your attention.

**Comment by ymjiang** [comment]
This is a duplicate issue with https://github.com/bytedance/byteps/issues/49. Your training already ended because you can see the test loss / accuracy from the log. That error was due to improper exiting of BytePS. We have fixed this. Please use the latest code.

Note: Please reformat your issue content. It is too messy and I can hardly read it.

**Comment by CDCrystal** [comment]
Many thx for your reply. I'm so sorry for the messy issue content since I wouldn't use that format editor before. I've re-edited it. This issue can be closed.
