### ISSUE TITLE
kvstore='device' cause `TypeError: bad operand type for unary -: 'str'`

### ISSUE THREAD

**Issue by Farrellow** [bytedance/byteps#73]
**Describe the bug**
I set kvstore='device' in model.fit() method, cause `byteps/byteps/mxnet/__init__.py line 50` the variable `index` is not int type but str type, and raise `TypeError: bad operand type for unary -: 'str'`

**To Reproduce**
1. the environments and codes are the same as [codes](https://github.com/bytedance/byteps/issues/67)
2. I just changed the arg `kvstore=None` to `kvstore='device'` in `model.fit() train_bps.py`
3. I got Exception
`
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 315, in 'calling callback function'
  File "/usr/local/lib/python2.7/dist-packages/mxnet/kvstore.py", line 85, in updater_handle
    updater(key, lhs, rhs)
  File "/usr/local/lib/python2.7/dist-packages/mxnet/optimizer/optimizer.py", line 1531, in __call__
    self.optimizer.update_multi_precision(index, weight, grad, self.states[index])
  File "/usr/local/lib/python2.7/dist-packages/byteps-0.1.0-py2.7-linux-x86_64.egg/byteps/mxnet/__init__.py", line 61, in update_multi_precision
    self._do_push_pull(index, grad)
  File "/usr/local/lib/python2.7/dist-packages/byteps-0.1.0-py2.7-linux-x86_64.egg/byteps/mxnet/__init__.py", line 52, in _do_push_pull
    byteps_push_pull(grad, version=0, priority=-index,
TypeError: bad operand type for unary -: 'str'
`
But the the worker process would not exit.
And I also found that the `index` which caused TypeError was the same as the `name` variable in `_update_params_on_kvstore() in mxnet/model.py` [mxnet/model.py](https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/model.py#L160)

**Environment (please complete the following information):**
 - OS: 16.04.3 LTS
 - GCC version: 4.9
 - CUDA and NCCL version:9.0 and d7a58cfa5865c4f627a128c3238cc72502649881
 - Framework (TF, PyTorch, MXNet):MXNet

**Comment by bobzhuyb** [comment]
Would you tell us what do you want to achieve? We did not expect users to use byteps with the native kvstore, since byteps does not require it at the worker side.
