### ISSUE TITLE
Error :  src/tcmalloc.cc:277] Attempt to free invalid pointer 0x7ffd819e4de8

### ISSUE THREAD

**Issue by mdztravelling** [bytedance/byteps#84]
Hi, I was following the Step-by-Step tutorial and try to build from the source code.
The single machine training (by 2 local GPUs) is work , but when I start to try run distributed training by change DMLC_NUM_WORKER=1 to DMLC_NUM_WORKER=2 failed.

I use framework is pytorch 1.1.0;

to
DMLC_NUM_WORKER=2

BytePS launching worker
training imagenet...
training imagenet...
[2019-08-15 21:05:10.113116: D byteps/common/communicator.cc:63] Using Communicator=Socket
[2019-08-15 21:05:10.113341: D byteps/common/communicator.cc:151] Init socket at /tmp/socket_send_1
[2019-08-15 21:05:10.113404: D byteps/common/communicator.cc:151] Init socket at /tmp/socket_recv_1
[2019-08-15 21:05:10.113489: D byteps/common/communicator.cc:121] This is ROOT device, rank=1, all sockets create successfully
[2019-08-15 21:05:10.113519: D byteps/common/global.cc:96] Partition bound set to 4096000 bytes, aligned to 4096000 bytes
[2019-08-15 21:05:10.113532: D byteps/common/global.cc:116] Number of worker=2, launching distributed job
[2019-08-15 21:05:10.113560: D byteps/common/communicator.cc:158] Listening on socket 1
[21:05:10] src/customer.cc:363: Do not use thread pool for receiving.
[21:05:10] src/./zmq_van.h:286: Start ZMQ recv thread
**src/tcmalloc.cc:277] Attempt to free invalid pointer 0x7ffd819e4de8** 
[2019-08-15 21:05:10.150423: D byteps/common/communicator.cc:63] Using Communicator=Socket
[2019-08-15 21:05:10.150598: D byteps/common/communicator.cc:151] Init socket at /tmp/socket_send_0
/home/work/test/bps_test/example/pytorch/start_pytorch_byteps.sh: line 21: 85279 Aborted                 $PYTHON $path/train_imagenet_resnet50_byteps.py $@
[2019-08-15 21:05:10.150653: D byteps/common/communicator.cc:151] Init socket at /tmp/socket_recv_0
[2019-08-15 21:05:10.150662: D byteps/common/communicator.cc:121] This is WORKER device, rank=0, all sockets create successfully
[2019-08-15 21:05:10.150675: D byteps/common/global.cc:96] Partition bound set to 4096000 bytes, aligned to 4096000 bytes
[2019-08-15 21:05:10.150686: D byteps/common/global.cc:116] Number of worker=2, launching distributed job
[2019-08-15 21:05:10.150747: D byteps/common/nccl_manager.cc:133] nccl_group_size set to 4
[2019-08-15 21:05:10.150756: D byteps/common/nccl_manager.cc:152] nccl_pcie_size set to 2
[2019-08-15 21:05:10.150762: D byteps/common/nccl_manager.cc:154] nccl_pcie_num set to 1
[2019-08-15 21:05:10.150769: D byteps/common/nccl_manager.cc:160] nccl_num_rings set to 1
[2019-08-15 21:05:10.150813: D byteps/common/communicator.cc:151] Init socket at /tmp/socket_send_nccl0
[2019-08-15 21:05:10.150847: D byteps/common/communicator.cc:151] Init socket at /tmp/socket_recv_nccl0
[2019-08-15 21:05:10.150854: D byteps/common/communicator.cc:55] This is nccl WORKER device, rank=0, all sockets create successfully
[2019-08-15 21:05:10.150860: D byteps/common/nccl_manager.cc:85] Constructing NCCL communicators. 0 1
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/work/test/bps_test/Python-2.7.14_torch-1.1_gcc5/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/work/test/bps_test/Python-2.7.14_torch-1.1_gcc5/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "launch.py", line 19, in worker
    subprocess.check_call(command, env=my_env, stdout=sys.stdout, stderr=sys.stderr, shell=True)
  File "/home/work/test/bps_test/Python-2.7.14_torch-1.1_gcc5/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '/home/work/test/bps_test/example/pytorch/start_pytorch_byteps.sh --batch-size=64 --workers=8 --train-dir=/home/nfs1/imagenet/imagenet_raw/train/ --val-dir=/home/nfs1/imagenet/imagenet_raw/val/' returned non-zero exit status 134

/home/work/test/bps_test/example/pytorch/start_pytorch_byteps.sh: line 21: 85280 Terminated              $PYTHON $path/train_imagenet_resnet50_byteps.py $@
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/work/test/bps_test/Python-2.7.14_torch-1.1_gcc5/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/work/test/bps_test/Python-2.7.14_torch-1.1_gcc5/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "launch.py", line 19, in worker
    subprocess.check_call(command, env=my_env, stdout=sys.stdout, stderr=sys.stderr, shell=True)
  File "/home/work/test/bps_test/Python-2.7.14_torch-1.1_gcc5/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '/home/work/test/bps_test/example/pytorch/start_pytorch_byteps.sh --batch-size=64 --workers=8 --train-dir=/home/nfs1/imagenet/imagenet_raw/train/ --val-dir=/home/nfs1/imagenet/imagenet_raw/val/' returned non-zero exit status 143

I installed libtcmalloc-minimal4 and setted LD_PRELOAD="/usr/lib/libtcmalloc_minimal.so.4", bug still error.

**Environment (please complete the following information):**
 - OS: CentOS 6.3
 - GCC version: 5.2
 - CUDA and NCCL version: 8.0, nccl2.2.12
 - Framework (TF, PyTorch, MXNet): PyTorch 1.1.0

How to solve this problem？
thanks!

**Comment by ymjiang** [comment]
Are you using the latest code? Could you provide the commit id of byteps and ps-lite? 

Also, looks like you are using gcc 5.2. Can you try to pin gcc to 4.9 ([example](https://github.com/bytedance/byteps/blob/master/docker/Dockerfile.worker.pytorch.cu100.rdma#L149-L157)) and then compile byteps again?

**Comment by mdztravelling** [comment]
@ymjiang 
yeah,  I use the latest code, byteps commit id is 53082ab, and ps-lite commitid is （6879d14）;
I setted environment variables  PATH、LD_LIBRARY_PATH, and gcc change to 4.9 and compile byteps again, but still error.

BytePS launching worker
training imagenet...
training imagenet...
[2019-08-16 11:56:53.666617: D byteps/common/communicator.cc:63] Using Communicator=Socket
[2019-08-16 11:56:53.666827: D byteps/common/communicator.cc:151] Init socket at /tmp/socket_send_0
[2019-08-16 11:56:53.666973: D byteps/common/communicator.cc:151] Init socket at /tmp/socket_recv_0
[2019-08-16 11:56:53.666995: D byteps/common/communicator.cc:121] This is WORKER device, rank=0, all sockets create successfully
[2019-08-16 11:56:53.667021: D byteps/common/global.cc:96] Partition bound set to 4096000 bytes, aligned to 4096000 bytes
[2019-08-16 11:56:53.667032: D byteps/common/global.cc:116] Number of worker=2, launching distributed job
[2019-08-16 11:56:53.667908: D byteps/common/nccl_manager.cc:133] nccl_group_size set to 4
[2019-08-16 11:56:53.667955: D byteps/common/nccl_manager.cc:152] nccl_pcie_size set to 2
[2019-08-16 11:56:53.667977: D byteps/common/nccl_manager.cc:154] nccl_pcie_num set to 1
[2019-08-16 11:56:53.667987: D byteps/common/nccl_manager.cc:160] nccl_num_rings set to 1
[2019-08-16 11:56:53.668079: D byteps/common/communicator.cc:151] Init socket at /tmp/socket_send_nccl0
[2019-08-16 11:56:53.668129: D byteps/common/communicator.cc:151] Init socket at /tmp/socket_recv_nccl0
[2019-08-16 11:56:53.668141: D byteps/common/communicator.cc:55] This is nccl WORKER device, rank=0, all sockets create successfully
[2019-08-16 11:56:53.668162: D byteps/common/nccl_manager.cc:85] Constructing NCCL communicators. 0 1
[2019-08-16 11:56:53.747637: D byteps/common/communicator.cc:63] Using Communicator=Socket
[2019-08-16 11:56:53.748909: D byteps/common/communicator.cc:151] Init socket at /tmp/socket_send_1
[2019-08-16 11:56:53.748980: D byteps/common/communicator.cc:151] Init socket at /tmp/socket_recv_1
[2019-08-16 11:56:53.749056: D byteps/common/communicator.cc:121] This is ROOT device, rank=1, all sockets create successfully
[2019-08-16 11:56:53.749086: D byteps/common/global.cc:96] Partition bound set to 4096000 bytes, aligned to 4096000 bytes
[2019-08-16 11:56:53.749102: D byteps/common/global.cc:116] Number of worker=2, launching distributed job
[2019-08-16 11:56:53.749143: D byteps/common/communicator.cc:158] Listening on socket 1
[11:56:53] src/customer.cc:363: Do not use thread pool for receiving.
[11:56:53] src/./zmq_van.h:286: Start ZMQ recv thread
**src/tcmalloc.cc:277] Attempt to free invalid pointer 0x7fff3efb99d8** 
/home/work/test/bps_test/example/pytorch/start_pytorch_byteps.sh: line 21: 68869 Aborted                 $PYTHON $path/train_imagenet_resnet50_byteps.py $@
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/work/test/bps_test/Python-2.7.14_torch-1.1_gcc49/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/work/test/bps_test/Python-2.7.14_torch-1.1_gcc49/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "launch.py", line 19, in worker
    subprocess.check_call(command, env=my_env, stdout=sys.stdout, stderr=sys.stderr, shell=True)
  File "/home/work/test/bps_test/Python-2.7.14_torch-1.1_gcc49/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '/home/work/test/bps_test/example/pytorch/start_pytorch_byteps.sh --batch-size=64 --workers=8 --train-dir=/home/nfs1/imagenet/imagenet_raw/train/ --val-dir=/home/nfs1/imagenet/imagenet_raw/val/' returned non-zero exit status 134

**Comment by bobzhuyb** [comment]
Can you paste your complete commands, including how you set the environment variables?
