### ISSUE TITLE
pytorch is crashing

### ISSUE THREAD

**Issue by arnaudfroidmont** [bytedance/byteps#96]
I've installed docker and all the nvidia drivers correctly. I can run  the tensorflow and the mxnet examples fine on my one GPU but pytorch seems to be crashing for me. Here is the error message:

`BytePS launching worker
running benchmark...
/usr/local/byteps/example/pytorch/start_pytorch_byteps.sh: line 20:    11 Floating point exception(core dumped) python $path/benchmark_byteps.py $@
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/byteps/launcher/launch.py", line 18, in worker
    subprocess.check_call(command, env=my_env, stdout=sys.stdout, stderr=sys.stderr, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '/usr/local/byteps/example/pytorch/start_pytorch_byteps.sh --model resnet50 --num-iters 100' returned non-zero exit status 136`

After digging around for a bit, It seems that the error is coming from the python code:

`import torch.backends.cudnn as cudnn`

Which is giving the error : 

`Floating point exception (core dumped)`

Any pointer?

**Comment by bobzhuyb** [comment]
Are you building your own docker image, or are you using the docker image we provided?

**Comment by arnaudfroidmont** [comment]
Using the one you provide. 
`docker pull bytepsimage/worker_pytorch`
